Pmemkv scripts
pmem/dev-utils-kit pull request #1
Opened 2021-01-22 11:17 UTC by tszczyp

Initial commit for jenkins libraries, it will be used for libpmemobj-cpp

2021-01-22 14:33 UTC, nedved1 reviewed
> Reviewed 2 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1)* status: 2 of 6 files reviewed, 3 unresolved discussions (waiting on @tszczyp)

___
*[jenkins/lib/api.groovy, line 4 at r1](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MReV22FBgzlZ9QIrSDv:-MReV22FBgzlZ9QIrSDw:bcc1xrr) ([raw file](https://github.com/pmem/dev-utils-kit/blob/1216cd5f264bfeafee4434430c58f3638deda2f3/jenkins/lib/api.groovy#L4)):*
> ```Groovy
> /* Copyright 2021, Intel Corporation */
> 
> /* Jenkinsfile - scripts to create pmemkv and pmemkv_matrix jobs - to run with initial jenkins job. */
> ```

You can delete this line.
___
*[jenkins/scripts/common.sh, line 57 at r1](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MReVAaUE3XT-L9LDXJP:-MReVAaUE3XT-L9LDXJQ:bjwos8i) ([raw file](https://github.com/pmem/dev-utils-kit/blob/1216cd5f264bfeafee4434430c58f3638deda2f3/jenkins/scripts/common.sh#L57)):*
> ```Shell
>  ___            ___
> /   \          /   \                            HELLO!
> \_   \        /  __/            THIS NODE IS CONNECTED TO PMEMKV JENKINS
> ```

Not only pmemkv
___
*[jenkins/scripts/createNamespace.sh, line 5 at r1](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MReVJDnDEz36pvnmzO2:-MReVJDoArttS8neKzsS:b-ymtq0e) ([raw file](https://github.com/pmem/dev-utils-kit/blob/1216cd5f264bfeafee4434430c58f3638deda2f3/jenkins/scripts/createNamespace.sh#L5)):*
> ```Shell
> # Copyright 2021, Intel Corporation
> 
> # createNamespace.sh - Remove old namespaces and create new for pmemkv tests.
> ```

not only pmemkv


<!-- Sent from Reviewable.io -->

2021-01-22 14:34 UTC, nedved1 reviewed
Please squash commits.

> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-:-MReW8YbEqawD75P_yVZ:b13bw5e)* status: 2 of 6 files reviewed, 3 unresolved discussions (waiting on @tszczyp)



<!-- Sent from Reviewable.io -->

2021-01-22 14:37 UTC, nedved1 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1)* status: 2 of 6 files reviewed, 4 unresolved discussions (waiting on @tszczyp)

___
*[README.md, line 1 at r1](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MReWioT4UUASrfu2dkK:-MReWioT4UUASrfu2dkL:b-t1n1ww) ([raw file](https://github.com/pmem/dev-utils-kit/blob/1216cd5f264bfeafee4434430c58f3638deda2f3/README.md#L1)):*
> ```Markdown
> # dev-utils-kit
> ```

Please add information about jenkins shared libraries and scripts.


<!-- Sent from Reviewable.io -->

2021-01-25 12:31 UTC, tszczyp reviewed
Done

> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-:-MRtW7lH488rdcQnY45M:bb6un1j)* status: 1 of 6 files reviewed, 4 unresolved discussions (waiting on @nedved1)

___
*[README.md, line 1 at r1](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MReWioT4UUASrfu2dkK:-MRtWCc4Aptopqbjpv8m:b-rrg7c2) ([raw file](https://github.com/pmem/dev-utils-kit/blob/1216cd5f264bfeafee4434430c58f3638deda2f3/README.md#L1)):*
<details><summary><i>Previously, nedved1 (Pawel Niedzwiecki) wrote…</i></summary><blockquote>

Please add information about jenkins shared libraries and scripts.
</blockquote></details>

Please check if current update is enough.
___
*[jenkins/lib/api.groovy, line 4 at r1](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MReV22FBgzlZ9QIrSDv:-MRtWV-MEInszWLVeeNh:b-896fix) ([raw file](https://github.com/pmem/dev-utils-kit/blob/1216cd5f264bfeafee4434430c58f3638deda2f3/jenkins/lib/api.groovy#L4)):*
<details><summary><i>Previously, nedved1 (Pawel Niedzwiecki) wrote…</i></summary><blockquote>

You can delete this line.
</blockquote></details>

Done.
___
*[jenkins/scripts/common.sh, line 57 at r1](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MReVAaUE3XT-L9LDXJP:-MRtWZmNAQisrTS_xoD_:b-a2ujfl) ([raw file](https://github.com/pmem/dev-utils-kit/blob/1216cd5f264bfeafee4434430c58f3638deda2f3/jenkins/scripts/common.sh#L57)):*
<details><summary><i>Previously, nedved1 (Pawel Niedzwiecki) wrote…</i></summary><blockquote>

Not only pmemkv
</blockquote></details>

Changed.
___
*[jenkins/scripts/createNamespace.sh, line 5 at r1](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MReVJDnDEz36pvnmzO2:-MRtWbLT2v-z4SwlgWXL:b-a2ujfl) ([raw file](https://github.com/pmem/dev-utils-kit/blob/1216cd5f264bfeafee4434430c58f3638deda2f3/jenkins/scripts/createNamespace.sh#L5)):*
<details><summary><i>Previously, nedved1 (Pawel Niedzwiecki) wrote…</i></summary><blockquote>

not only pmemkv
</blockquote></details>

Changed.


<!-- Sent from Reviewable.io -->

2021-01-26 11:37 UTC, nedved1 reviewed
thx

> Reviewed 1 of 6 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-:-MRyTG8IBjQBjsZX_Jn_:b2nid0f)* status: all files reviewed, 4 unresolved discussions (waiting on @tszczyp)

___
*[README.md, line 1 at r1](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MReWioT4UUASrfu2dkK:-MRyTLDg6xqsLFJXA3lW:b2fngst) ([raw file](https://github.com/pmem/dev-utils-kit/blob/1216cd5f264bfeafee4434430c58f3638deda2f3/README.md#L1)):*
<details><summary><i>Previously, tszczyp (Tomasz Szczypiorowski) wrote…</i></summary><blockquote>

Please check if current update is enough.
</blockquote></details>

looks ok
___
*[jenkins/lib/api.groovy, line 4 at r1](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MReV22FBgzlZ9QIrSDv:-MRyTOaNDm5hVUhW5s4j:b2nid0f) ([raw file](https://github.com/pmem/dev-utils-kit/blob/1216cd5f264bfeafee4434430c58f3638deda2f3/jenkins/lib/api.groovy#L4)):*
<details><summary><i>Previously, tszczyp (Tomasz Szczypiorowski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

thx
___
*[jenkins/scripts/common.sh, line 57 at r1](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MReVAaUE3XT-L9LDXJP:-MRyT_hR4Dr-s9reJAjN:b2nid0f) ([raw file](https://github.com/pmem/dev-utils-kit/blob/1216cd5f264bfeafee4434430c58f3638deda2f3/jenkins/scripts/common.sh#L57)):*
<details><summary><i>Previously, tszczyp (Tomasz Szczypiorowski) wrote…</i></summary><blockquote>

Changed.
</blockquote></details>

thx
___
*[jenkins/scripts/createNamespace.sh, line 5 at r1](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MReVJDnDEz36pvnmzO2:-MRyTd1L-u9KBLOGV2TO:b2nid0f) ([raw file](https://github.com/pmem/dev-utils-kit/blob/1216cd5f264bfeafee4434430c58f3638deda2f3/jenkins/scripts/createNamespace.sh#L5)):*
<details><summary><i>Previously, tszczyp (Tomasz Szczypiorowski) wrote…</i></summary><blockquote>

Changed.
</blockquote></details>

thx


<!-- Sent from Reviewable.io -->

2021-03-22 13:31 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 6 files at r1, 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1)* status: all files reviewed, 12 unresolved discussions (waiting on @tszczyp)

*[a discussion](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MWP6u0d1Dl59jHGSa8O:-MWP6u0d1Dl59jHGSa8P:b80jjpj) (no related file):*
I know it's just a draft, but please remember to cleanup the commit message, to only get the final information what was added, not change history :) (the sign-off should be the last part, by the way)

---
___
*[jenkins/README.md, line 11 at r2](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MWP3yj61tSq3xIHBSHv:-MWP3yj61tSq3xIHBSHw:biyxh8z) ([raw file](https://github.com/pmem/dev-utils-kit/blob/16e2945493f93355b054f3d2e4125df6a0834ef1/jenkins/README.md#L11)):*
> ```Markdown
> Jenkins is a self contained, open sourced automation server which can be used to automate tasks related to building and testing. Its functionality can be expanded by installing plugins.
> 
> Jenkins main function is to launch jobs. Jobs are scripts that cover managing repositories, building and testing. Jenkins pipeline is a script that is launched by Jenkins job. Each pipeline consists of build stages that follow one another, for example: download repository, build, test, etc. Each stage consists of steps that are actual commands ran on an actual device under test - which which is called: Node.
> ```

`which which` -> `which`
___
*[jenkins/README.md, line 69 at r2](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MWP6l_H-KzegCD1dEkB:-MWP6l_H-KzegCD1dEkC:bbf68ip) ([raw file](https://github.com/pmem/dev-utils-kit/blob/16e2945493f93355b054f3d2e4125df6a0834ef1/jenkins/README.md#L69)):*
> ```Markdown
> - Select: "Pipeline".
> - Click OK.
> - In tab "General", select "GitHUB Project", enter project url: "https://github.com/pmem/pmemkv".
> ```

`enter project url, e.g.: ...`
___
*[jenkins/README.md, line 74 at r2](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MWP6qDh8wbB1rO3cGev:-MWP6qDiDZrwcpWkfgWr:b3kqx) ([raw file](https://github.com/pmem/dev-utils-kit/blob/16e2945493f93355b054f3d2e4125df6a0834ef1/jenkins/README.md#L74)):*
> ```Markdown
>     - SCM: Git
>     - Repositories:
>       - Repository URL: Enter github repository with jenkins job, e.g. "https://github.com/pmem/pmemkv".
> ```

.
___
*[jenkins/README.md, line 80 at r2](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MWP4G508RBGxIRFnPTT:-MWP4G508RBGxIRFnPTU:b-66kp9m) ([raw file](https://github.com/pmem/dev-utils-kit/blob/16e2945493f93355b054f3d2e4125df6a0834ef1/jenkins/README.md#L80)):*
> ```Markdown
>     - Script Path: Enter path with the Jenkinsfile, relative to the root folder of the repository: "utils/jenkins/Jenkinsfile"
>     - Lightweight checkout: yes
> 7. Save.
> ```

random 7., 8., 9. ;) make it all either numerated or non-numerated list
___
*[jenkins/lib/api.groovy, line 17 at r2](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MWP4pHUARD3AnInec1j:-MWP4pHUARD3AnInec1k:bib6yww) ([raw file](https://github.com/pmem/dev-utils-kit/blob/16e2945493f93355b054f3d2e4125df6a0834ef1/jenkins/lib/api.groovy#L17)):*
> ```Groovy
> OUTPUT_DIR = "${WORKSPACE_DIR}/${OUTPUT_DIR_NAME}"
> RESULTS_DIR = "${WORKSPACE_DIR}/${RESULTS_DIR_NAME}"
> SCRIPTS_DIR = "${WORKSPACE_DIR}/jenkins_files/utils/jenkins/scripts"
> ```

where does this `jenkins_files` come from?
___
*[jenkins/lib/api.groovy, line 358 at r2](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MWP5Qln8kqhwKsprOtO:-MWP5Qlo7LlGGu2gHOfV:b-x31a05) ([raw file](https://github.com/pmem/dev-utils-kit/blob/16e2945493f93355b054f3d2e4125df6a0834ef1/jenkins/lib/api.groovy#L358)):*
> ```Groovy
> 	def get_html_table_data_row() {
> 		def urls =
> 				"<a href=\"${env.JENKINS_URL}blue/organizations/jenkins/${currentBuild.projectName}/detail/${currentBuild.projectName}/${currentBuild.id}/pipeline\">blue</a>, <a href=\"${env.JENKINS_URL}blue/organizations/jenkins/${currentBuild.projectName}/detail/${currentBuild.projectName}/${currentBuild.id}/tests\">blue tests</a>, <a href=\"${env.JENKINS_URL}view/all/job/${currentBuild.projectName}/${currentBuild.id}/testReport\">tests</a>, <a href=\"${env.JENKINS_URL}view/all/job/${currentBuild.projectName}/${currentBuild.id}/\">build</a>, <a href=\"${env.JENKINS_URL}view/all/job/${currentBuild.projectName}/${currentBuild.id}/consoleText\">console</a>, <a href=\"${env.JENKINS_URL}job/${currentBuild.projectName}/${currentBuild.id}/artifact/results/system_info.txt\">system_info</a>"
> ```

are you sure that string held by `env.JENKINS_URL` always ends with `/` character? If not, there should be `${env.JENKINS_URL}/blue...` (here and in other places, as well). At worst there will be double `//` and it should not bother us.
___
*[jenkins/scripts/common.sh, line 20 at r2](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MWP7PDyCeCUuaHFoyWY:-MWP7PDyCeCUuaHFoyWZ:b-27k71m) ([raw file](https://github.com/pmem/dev-utils-kit/blob/16e2945493f93355b054f3d2e4125df6a0834ef1/jenkins/scripts/common.sh#L20)):*
> ```Shell
> 	echo "libpmemobj: $(pkg-config --modversion libpmemobj || echo 'libpmemobj not found')"
> 	echo "libpmemobj++: $(pkg-config --modversion libpmemobj++ || echo 'libpmemobj++ not found')"
> 	echo "memkind: $(pkg-config --modversion memkind || echo 'memkind not found')"
> ```

please also add printing status of libpmemkv


<!-- Sent from Reviewable.io -->

2021-03-23 14:05 UTC, tszczyp reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1)* status: 3 of 6 files reviewed, 12 unresolved discussions (waiting on @lukaszstolarczuk, @nedved1, and @tszczyp)

*[a discussion](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MWP6u0d1Dl59jHGSa8O:-MWUN3FP1Vabg9gnuNSm:b-gewwb3) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I know it's just a draft, but please remember to cleanup the commit message, to only get the final information what was added, not change history :) (the sign-off should be the last part, by the way)
</blockquote></details>

Commit message updated :)

---
___
*[README.md, line 1 at r1](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MReWioT4UUASrfu2dkK:-MWUOkpv78AlxRdKCyT9:b-896fix) ([raw file](https://github.com/pmem/dev-utils-kit/blob/1216cd5f264bfeafee4434430c58f3638deda2f3/README.md#L1)):*
<details><summary><i>Previously, nedved1 (Pawel Niedzwiecki) wrote…</i></summary><blockquote>

looks ok
</blockquote></details>

Done.
___
*[jenkins/README.md, line 11 at r2](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MWP3yj61tSq3xIHBSHv:-MWUNJ3kBQ5VwkFyy0Pt:bb6un1j) ([raw file](https://github.com/pmem/dev-utils-kit/blob/16e2945493f93355b054f3d2e4125df6a0834ef1/jenkins/README.md#L11)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`which which` -> `which`
</blockquote></details>

Done
___
*[jenkins/README.md, line 69 at r2](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MWP6l_H-KzegCD1dEkB:-MWUNVzRD3_Fk7ox3trQ:b-a2ujfl) ([raw file](https://github.com/pmem/dev-utils-kit/blob/16e2945493f93355b054f3d2e4125df6a0834ef1/jenkins/README.md#L69)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`enter project url, e.g.: ...`
</blockquote></details>

Changed.
___
*[jenkins/README.md, line 80 at r2](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MWP4G508RBGxIRFnPTT:-MWUO3cJ5Zl7gj_t0F-0:baq6f8t) ([raw file](https://github.com/pmem/dev-utils-kit/blob/16e2945493f93355b054f3d2e4125df6a0834ef1/jenkins/README.md#L80)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

random 7., 8., 9. ;) make it all either numerated or non-numerated list
</blockquote></details>

Changed for non-numerated list.
___
*[jenkins/lib/api.groovy, line 17 at r2](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MWP4pHUARD3AnInec1j:-MWUOBEC3gmWFi406s9a:bsjh949) ([raw file](https://github.com/pmem/dev-utils-kit/blob/16e2945493f93355b054f3d2e4125df6a0834ef1/jenkins/lib/api.groovy#L17)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

where does this `jenkins_files` come from?
</blockquote></details>

Path updated, mistake on my side.
___
*[jenkins/lib/api.groovy, line 358 at r2](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MWP5Qln8kqhwKsprOtO:-MWUOLNd-WWQu_vtpDD0:b-bh0pvs) ([raw file](https://github.com/pmem/dev-utils-kit/blob/16e2945493f93355b054f3d2e4125df6a0834ef1/jenkins/lib/api.groovy#L358)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

are you sure that string held by `env.JENKINS_URL` always ends with `/` character? If not, there should be `${env.JENKINS_URL}/blue...` (here and in other places, as well). At worst there will be double `//` and it should not bother us.
</blockquote></details>

I wasn't sure, so '/' added.
___
*[jenkins/scripts/common.sh, line 57 at r1](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MReVAaUE3XT-L9LDXJP:-MWUOdKl-N5nIwUUo6eL:b-896fix) ([raw file](https://github.com/pmem/dev-utils-kit/blob/1216cd5f264bfeafee4434430c58f3638deda2f3/jenkins/scripts/common.sh#L57)):*
<details><summary><i>Previously, nedved1 (Pawel Niedzwiecki) wrote…</i></summary><blockquote>

thx
</blockquote></details>

Done.
___
*[jenkins/scripts/common.sh, line 20 at r2](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MWP7PDyCeCUuaHFoyWY:-MWUORpR9t_th-C-0Dm8:b-kvbz6y) ([raw file](https://github.com/pmem/dev-utils-kit/blob/16e2945493f93355b054f3d2e4125df6a0834ef1/jenkins/scripts/common.sh#L20)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

please also add printing status of libpmemkv
</blockquote></details>

Printing added, let me know if I didn't make a mistake with its name :D
___
*[jenkins/scripts/createNamespace.sh, line 5 at r1](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MReVJDnDEz36pvnmzO2:-MWUOfqND4ydrdeVnbOt:b-896fix) ([raw file](https://github.com/pmem/dev-utils-kit/blob/1216cd5f264bfeafee4434430c58f3638deda2f3/jenkins/scripts/createNamespace.sh#L5)):*
<details><summary><i>Previously, nedved1 (Pawel Niedzwiecki) wrote…</i></summary><blockquote>

thx
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-23 18:13 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 6 files at r1, 1 of 4 files at r2, 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1)* status: 4 of 6 files reviewed, 6 unresolved discussions (waiting on @nedved1 and @tszczyp)

___
*[jenkins/lib/api.groovy, line 358 at r2](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MWP5Qln8kqhwKsprOtO:-MWVHNpr5dF_z9DaAqdH:blzb892) ([raw file](https://github.com/pmem/dev-utils-kit/blob/16e2945493f93355b054f3d2e4125df6a0834ef1/jenkins/lib/api.groovy#L358)):*
<details><summary><i>Previously, tszczyp (Tomasz Szczypiorowski) wrote…</i></summary><blockquote>

I wasn't sure, so '/' added.
</blockquote></details>

you missed one place (for tests link, I believe)
___
*[jenkins/scripts/common.sh, line 20 at r2](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MWP7PDyCeCUuaHFoyWY:-MWVH4AhA-8_1E3jN4dx:b-4s5r2n) ([raw file](https://github.com/pmem/dev-utils-kit/blob/16e2945493f93355b054f3d2e4125df6a0834ef1/jenkins/scripts/common.sh#L20)):*
<details><summary><i>Previously, tszczyp (Tomasz Szczypiorowski) wrote…</i></summary><blockquote>

Printing added, let me know if I didn't make a mistake with its name :D
</blockquote></details>

looks good, just please align echo with other commands (tab instead of spaces, I believe) 


<!-- Sent from Reviewable.io -->

2021-03-30 10:02 UTC, tszczyp reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1)* status: 4 of 6 files reviewed, 6 unresolved discussions (waiting on @lukaszstolarczuk and @nedved1)

___
*[jenkins/README.md, line 74 at r2](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MWP6qDh8wbB1rO3cGev:-MX1_Gtt7cY3cm7w7z7j:b-896fix) ([raw file](https://github.com/pmem/dev-utils-kit/blob/16e2945493f93355b054f3d2e4125df6a0834ef1/jenkins/README.md#L74)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[jenkins/lib/api.groovy, line 358 at r2](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MWP5Qln8kqhwKsprOtO:-MX1_IY-B2n7jaSOpX6q:b-wtr871) ([raw file](https://github.com/pmem/dev-utils-kit/blob/16e2945493f93355b054f3d2e4125df6a0834ef1/jenkins/lib/api.groovy#L358)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you missed one place (for tests link, I believe)
</blockquote></details>

You're right, updated.
___
*[jenkins/scripts/common.sh, line 20 at r2](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MWP7PDyCeCUuaHFoyWY:-MX1_Q1MDO_xFLnWUW9a:b-cszsw0) ([raw file](https://github.com/pmem/dev-utils-kit/blob/16e2945493f93355b054f3d2e4125df6a0834ef1/jenkins/scripts/common.sh#L20)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

looks good, just please align echo with other commands (tab instead of spaces, I believe) 
</blockquote></details>

Modified.


<!-- Sent from Reviewable.io -->

2021-03-30 15:43 UTC, lukaszstolarczuk reviewed
:+1: 

> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-:-MX2nJ40C3w9vwyktYeg:b-8fx2u7)* status: all files reviewed, 4 unresolved discussions (waiting on @nedved1)



<!-- Sent from Reviewable.io -->

2021-04-06 16:58 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1)* status: all files reviewed, 4 unresolved discussions (waiting on @nedved1)



<!-- Sent from Reviewable.io -->

2021-04-19 08:16 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1)* status: 4 of 6 files reviewed, 6 unresolved discussions (waiting on @lukaszstolarczuk, @nedved1, and @tszczyp)

___
*[jenkins/lib/api.groovy, line 154 at r6](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MYdBe3g8_Nv-QUOCFLM:-MYdBe3g8_Nv-QUOCFLN:b-18477o) ([raw file](https://github.com/pmem/dev-utils-kit/blob/5e928b6435d937b7f1cec3487fb4f24fe7dcc2f7/jenkins/lib/api.groovy#L154)):*
> ```Groovy
>  * @param repo_sha SHA of repository revision.
>  */
> def remember_git_revision(repo_url, repo_sha) {
> ```

why do we need this remembering?
___
*[jenkins/scripts/createNamespace.sh, line 47 at r2](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MYdB1dTEXJAH83L6AlK:-MYdB1dTEXJAH83L6AlL:borsaf0) ([raw file](https://github.com/pmem/dev-utils-kit/blob/16e2945493f93355b054f3d2e4125df6a0834ef1/jenkins/scripts/createNamespace.sh#L47)):*
> ```Shell
> 
> function create_fsdax() {
> 	echo "Creating fsdax namespace"
> ```

why removed?


<!-- Sent from Reviewable.io -->

2021-04-19 08:17 UTC, lukaszstolarczuk commented
@tszczyp, I guess you can un-draft this

2021-04-19 09:21 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1)* status: 4 of 6 files reviewed, 7 unresolved discussions (waiting on @lukaszstolarczuk, @nedved1, and @tszczyp)

___
*[jenkins/scripts/common.sh, line 41 at r6](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MYdQi7cCL2opGEdQR8h:-MYdQi7cCL2opGEdQR8i:b-r36d7w) ([raw file](https://github.com/pmem/dev-utils-kit/blob/5e928b6435d937b7f1cec3487fb4f24fe7dcc2f7/jenkins/scripts/common.sh#L41)):*
> ```Shell
> 	echo "**********/proc/meminfo**********"
> 	cat /proc/meminfo
> 	eco "**********/proc/swaps**********"
> ```

`eco` -> `echo`


<!-- Sent from Reviewable.io -->

2021-04-20 14:30 UTC, tszczyp reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1)* status: 3 of 6 files reviewed, 7 unresolved discussions (waiting on @lukaszstolarczuk and @nedved1)

___
*[jenkins/lib/api.groovy, line 154 at r6](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MYdBe3g8_Nv-QUOCFLM:-MYjfbPn232ZJ1yUjUIk:b-htm44y) ([raw file](https://github.com/pmem/dev-utils-kit/blob/5e928b6435d937b7f1cec3487fb4f24fe7dcc2f7/jenkins/lib/api.groovy#L154)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

why do we need this remembering?
</blockquote></details>

After each build, commit's sha will be archived which we thought would be useful
![image.png](https://files.reviewableusercontent.io/images/reviewable/25879106/qk10L1QG9Rn2BoUz9ubjRrDZ/image.png)
![image copy 1.png](https://files.reviewableusercontent.io/images/reviewable/25879106/-XwOHmv1ifg4VcxvHdTzWd39/image.png)
___
*[jenkins/scripts/common.sh, line 41 at r6](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MYdQi7cCL2opGEdQR8h:-MYjdG1MCk0whLUmxbXA:b-896fix) ([raw file](https://github.com/pmem/dev-utils-kit/blob/5e928b6435d937b7f1cec3487fb4f24fe7dcc2f7/jenkins/scripts/common.sh#L41)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`eco` -> `echo`
</blockquote></details>

Done.
___
*[jenkins/scripts/createNamespace.sh, line 47 at r2](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MYdB1dTEXJAH83L6AlK:-MYjdJ4J7A4Xd5WiIM32:b-bollxt) ([raw file](https://github.com/pmem/dev-utils-kit/blob/16e2945493f93355b054f3d2e4125df6a0834ef1/jenkins/scripts/createNamespace.sh#L47)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

why removed?
</blockquote></details>

This echo was causing an error while creating fsdax namespaces, its content was made a part of pmem_name variable
![image.png](https://files.reviewableusercontent.io/images/reviewable/25879106/-1wVYnGk2rCNCslDICAu_Mvb/image.png)

Which made mounting them impossible, due to non existent device
![image copy 1.png](https://files.reviewableusercontent.io/images/reviewable/25879106/0i0N4O5LKge48GKK5FvmHBIJ/image.png)

Result:
![image copy 2.png](https://files.reviewableusercontent.io/images/reviewable/25879106/8SplzhGIbuwJmKpaFBU0cNeC/image.png)


<!-- Sent from Reviewable.io -->

2021-04-21 08:51 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 2 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1)* status: 5 of 6 files reviewed, 16 unresolved discussions (waiting on @lukaszstolarczuk, @nedved1, and @tszczyp)

___
*[jenkins/lib/api.groovy, line 2 at r7](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MYnbG-061B8hWDK7QbE:-MYnbG-061B8hWDK7QbF:b-akd4hx) ([raw file](https://github.com/pmem/dev-utils-kit/blob/66935e7d9b55448180718fd0dc0a840c9f1bc56a/jenkins/lib/api.groovy#L2)):*
> ```Groovy
> // SPDX-License-Identifier: BSD-3-Clause
> /* Copyright 2021, Intel Corporation */
> ```

I guess all those files were copied, so they should have the original dates, not just "2021"
___
*[jenkins/lib/api.groovy, line 28 at r7](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MYnTW6O3lACCSo0nGbB:-MYnTW6P2KTBrOEgSKzA:b-yvuvx9) ([raw file](https://github.com/pmem/dev-utils-kit/blob/66935e7d9b55448180718fd0dc0a840c9f1bc56a/jenkins/lib/api.groovy#L28)):*
> ```Groovy
> COMMON_FILE = "${SCRIPTS_DIR}/common.sh"
> 
> REVISION_VERSION_FILENAME = "sha.txt"
> ```

just REVISIONS_FILENAME should be enough
___
*[jenkins/lib/api.groovy, line 31 at r7](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MYnTj_85Qwggh7nYKF6:-MYnTj_85Qwggh7nYKF7:b-bw3qaf) ([raw file](https://github.com/pmem/dev-utils-kit/blob/66935e7d9b55448180718fd0dc0a840c9f1bc56a/jenkins/lib/api.groovy#L31)):*
> ```Groovy
> 
> 
> // list of known git revisions, should contains list of dicts with .url and .sha keys
> ```

make this  a /**/ comment
___
*[jenkins/lib/api.groovy, line 31 at r7](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MYnTln0EsEQwunPAclg:-MYnTln0EsEQwunPAclh:b-azxm0d) ([raw file](https://github.com/pmem/dev-utils-kit/blob/66935e7d9b55448180718fd0dc0a840c9f1bc56a/jenkins/lib/api.groovy#L31)):*
> ```Groovy
> 
> 
> // list of known git revisions, should contains list of dicts with .url and .sha keys
> ```

`List of git revisions used in a job. It should contain list of dicts (with 'url' and 'sha' keys)`
___
*[jenkins/lib/api.groovy, line 32 at r7](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MYnU4L-8yRwHguOY2vZ:-MYnU4L-8yRwHguOY2v_:b2gqprc) ([raw file](https://github.com/pmem/dev-utils-kit/blob/66935e7d9b55448180718fd0dc0a840c9f1bc56a/jenkins/lib/api.groovy#L32)):*
> ```Groovy
> 
> // list of known git revisions, should contains list of dicts with .url and .sha keys
> known_git_revisions = []
> ```

rename to just `git_revisions`? or maybe `saved_git_revisions`...? "known" seems a bit odd to me (I don't know why :D)
___
*[jenkins/lib/api.groovy, line 148 at r7](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MYna7Nq1ga1Hjg0R_gv:-MYna7Nq1ga1Hjg0R_gw:b85y50n) ([raw file](https://github.com/pmem/dev-utils-kit/blob/66935e7d9b55448180718fd0dc0a840c9f1bc56a/jenkins/lib/api.groovy#L148)):*
> ```Groovy
> 
> /**
>  * Add repository revision to known revisions. This is used for example to send e-mail with test result.
> ```

is it used in e-mails?
___
*[jenkins/lib/api.groovy, line 149 at r7](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MYnaBiDA5iVrK57Hrkb:-MYnaBiDA5iVrK57Hrkc:b-td8kfy) ([raw file](https://github.com/pmem/dev-utils-kit/blob/66935e7d9b55448180718fd0dc0a840c9f1bc56a/jenkins/lib/api.groovy#L149)):*
> ```Groovy
> /**
>  * Add repository revision to known revisions. This is used for example to send e-mail with test result.
>  * If requested repository (matching URL and SHA) is already known, it is not added second time.
> ```

it's not added **for** the second time
___
*[jenkins/lib/api.groovy, line 151 at r7](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MYnaGtmC3wFmY0i2uFP:-MYnaGtmC3wFmY0i2uFQ:b8mqbu5) ([raw file](https://github.com/pmem/dev-utils-kit/blob/66935e7d9b55448180718fd0dc0a840c9f1bc56a/jenkins/lib/api.groovy#L151)):*
> ```Groovy
>  * If requested repository (matching URL and SHA) is already known, it is not added second time.
>  * However - if, for example, provided repo was added previously with different SHA, it will be added as separate entry.
>  * @param repo_url URL of repository.
> ```

of a repository
___
*[jenkins/lib/api.groovy, line 152 at r7](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MYnaJv022lJgOhjCm0R:-MYnaJv022lJgOhjCm0S:b3kqx) ([raw file](https://github.com/pmem/dev-utils-kit/blob/66935e7d9b55448180718fd0dc0a840c9f1bc56a/jenkins/lib/api.groovy#L152)):*
> ```Groovy
>  * However - if, for example, provided repo was added previously with different SHA, it will be added as separate entry.
>  * @param repo_url URL of repository.
>  * @param repo_sha SHA of repository revision.
> ```

.
___
*[jenkins/lib/api.groovy, line 154 at r7](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MYnULzf096CNi2hZyA2:-MYnULzf096CNi2hZyA3:bxmnhzd) ([raw file](https://github.com/pmem/dev-utils-kit/blob/66935e7d9b55448180718fd0dc0a840c9f1bc56a/jenkins/lib/api.groovy#L154)):*
> ```Groovy
>  * @param repo_sha SHA of repository revision.
>  */
> def remember_git_revision(repo_url, repo_sha) {
> ```

`remember` -> `save` ?
___
*[jenkins/lib/api.groovy, line 164 at r7](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MYn_j-78lvOSoIfXYzh:-MYn_j-8BKq9_6ktXnyX:bgqv9h1) ([raw file](https://github.com/pmem/dev-utils-kit/blob/66935e7d9b55448180718fd0dc0a840c9f1bc56a/jenkins/lib/api.groovy#L164)):*
> ```Groovy
> 
> /**
>  * Return git revision string of all cloned repositories.
> ```

`of all` -> `with all`
___
*[jenkins/scripts/createNamespace.sh, line 47 at r2](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MYdB1dTEXJAH83L6AlK:-MYnZdXu0S5MCaxo70hx:bkc6fvc) ([raw file](https://github.com/pmem/dev-utils-kit/blob/16e2945493f93355b054f3d2e4125df6a0834ef1/jenkins/scripts/createNamespace.sh#L47)):*
<details><summary><i>Previously, tszczyp (Tomasz Szczypiorowski) wrote…</i></summary><blockquote>

This echo was causing an error while creating fsdax namespaces, its content was made a part of pmem_name variable
![image.png](https://files.reviewableusercontent.io/images/reviewable/25879106/-1wVYnGk2rCNCslDICAu_Mvb/image.png)

Which made mounting them impossible, due to non existent device
![image copy 1.png](https://files.reviewableusercontent.io/images/reviewable/25879106/0i0N4O5LKge48GKK5FvmHBIJ/image.png)

Result:
![image copy 2.png](https://files.reviewableusercontent.io/images/reviewable/25879106/8SplzhGIbuwJmKpaFBU0cNeC/image.png)

</blockquote></details>

hmm ok, then you can:
1. add `echo "$result"` at the end of the function
2. move the deleted echo into the `if $CREATE_PMEM`


<!-- Sent from Reviewable.io -->

2021-04-22 12:37 UTC, tszczyp reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1)* status: 3 of 6 files reviewed, 16 unresolved discussions (waiting on @lukaszstolarczuk and @nedved1)

___
*[jenkins/lib/api.groovy, line 2 at r7](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MYnbG-061B8hWDK7QbE:-MYtY75j4Yy6JAuodvir:b-a2ujfl) ([raw file](https://github.com/pmem/dev-utils-kit/blob/66935e7d9b55448180718fd0dc0a840c9f1bc56a/jenkins/lib/api.groovy#L2)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I guess all those files were copied, so they should have the original dates, not just "2021"
</blockquote></details>

Changed.
___
*[jenkins/lib/api.groovy, line 28 at r7](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MYnTW6O3lACCSo0nGbB:-MYtYCGI1Z00vXxzAgMN:b-896fix) ([raw file](https://github.com/pmem/dev-utils-kit/blob/66935e7d9b55448180718fd0dc0a840c9f1bc56a/jenkins/lib/api.groovy#L28)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

just REVISIONS_FILENAME should be enough
</blockquote></details>

Done.
___
*[jenkins/lib/api.groovy, line 31 at r7](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MYnTj_85Qwggh7nYKF6:-MYtYD1y2HZmKgW0X_KT:b-bw8e14) ([raw file](https://github.com/pmem/dev-utils-kit/blob/66935e7d9b55448180718fd0dc0a840c9f1bc56a/jenkins/lib/api.groovy#L31)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

make this  a /**/ comment
</blockquote></details>

Updated.
___
*[jenkins/lib/api.groovy, line 31 at r7](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MYnTln0EsEQwunPAclg:-MYtZaUjCNs2m6IHZzVa:b-cszsw0) ([raw file](https://github.com/pmem/dev-utils-kit/blob/66935e7d9b55448180718fd0dc0a840c9f1bc56a/jenkins/lib/api.groovy#L31)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`List of git revisions used in a job. It should contain list of dicts (with 'url' and 'sha' keys)`
</blockquote></details>

Modified.
___
*[jenkins/lib/api.groovy, line 32 at r7](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MYnU4L-8yRwHguOY2vZ:-MYtZeJFAHOe5a-hAuOF:b-pf6bpd) ([raw file](https://github.com/pmem/dev-utils-kit/blob/66935e7d9b55448180718fd0dc0a840c9f1bc56a/jenkins/lib/api.groovy#L32)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

rename to just `git_revisions`? or maybe `saved_git_revisions`...? "known" seems a bit odd to me (I don't know why :D)
</blockquote></details>

Changed to saved_git_revisions
___
*[jenkins/lib/api.groovy, line 148 at r7](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MYna7Nq1ga1Hjg0R_gv:-MYtZhTg-JpFAb09pGp-:b-yus9b8) ([raw file](https://github.com/pmem/dev-utils-kit/blob/66935e7d9b55448180718fd0dc0a840c9f1bc56a/jenkins/lib/api.groovy#L148)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

is it used in e-mails?
</blockquote></details>

umm....no, but it will be :v
___
*[jenkins/lib/api.groovy, line 149 at r7](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MYnaBiDA5iVrK57Hrkb:-MYtZlvX80VEupKjCnu8:b-896fix) ([raw file](https://github.com/pmem/dev-utils-kit/blob/66935e7d9b55448180718fd0dc0a840c9f1bc56a/jenkins/lib/api.groovy#L149)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

it's not added **for** the second time
</blockquote></details>

Done.
___
*[jenkins/lib/api.groovy, line 151 at r7](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MYnaGtmC3wFmY0i2uFP:-MYtZtja081wan6T9vYw:b-896fix) ([raw file](https://github.com/pmem/dev-utils-kit/blob/66935e7d9b55448180718fd0dc0a840c9f1bc56a/jenkins/lib/api.groovy#L151)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

of a repository
</blockquote></details>

Done.
___
*[jenkins/lib/api.groovy, line 152 at r7](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MYnaJv022lJgOhjCm0R:-MYtZuHIAqYJXFtLKp1k:b-896fix) ([raw file](https://github.com/pmem/dev-utils-kit/blob/66935e7d9b55448180718fd0dc0a840c9f1bc56a/jenkins/lib/api.groovy#L152)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[jenkins/lib/api.groovy, line 154 at r7](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MYnULzf096CNi2hZyA2:-MYtZvE_DEvh6oGiMTML:b-a2ujfl) ([raw file](https://github.com/pmem/dev-utils-kit/blob/66935e7d9b55448180718fd0dc0a840c9f1bc56a/jenkins/lib/api.groovy#L154)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`remember` -> `save` ?
</blockquote></details>

Changed.
___
*[jenkins/lib/api.groovy, line 164 at r7](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MYn_j-78lvOSoIfXYzh:-MYtZxEs8HkXh9d4FJhN:b-896fix) ([raw file](https://github.com/pmem/dev-utils-kit/blob/66935e7d9b55448180718fd0dc0a840c9f1bc56a/jenkins/lib/api.groovy#L164)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`of all` -> `with all`
</blockquote></details>

Done.
___
*[jenkins/scripts/createNamespace.sh, line 47 at r2](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MYdB1dTEXJAH83L6AlK:-MYtZyeX1qZ_QwUOVw_u:b-x8e7vr) ([raw file](https://github.com/pmem/dev-utils-kit/blob/16e2945493f93355b054f3d2e4125df6a0834ef1/jenkins/scripts/createNamespace.sh#L47)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

hmm ok, then you can:
1. add `echo "$result"` at the end of the function
2. move the deleted echo into the `if $CREATE_PMEM`
</blockquote></details>

Unfortunately, as I checked, adding any echo in that function, even at the end, caused errors in its functionality so I couldn't add it, although I moved original echo to if $CREATE_PMEM as requested.


<!-- Sent from Reviewable.io -->

2021-04-22 13:26 UTC, lukaszstolarczuk reviewed
> Reviewed 3 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1)* status: all files reviewed, 9 unresolved discussions (waiting on @nedved1 and @tszczyp)

*[a discussion](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MWP6u0d1Dl59jHGSa8O:-MYtjTbZ9MqphnTp4uJs:b-aip4lg) (no related file):*
<details><summary><i>Previously, tszczyp (Tomasz Szczypiorowski) wrote…</i></summary><blockquote>

Commit message updated :)
</blockquote></details>

it says "pmemkv libs and scripts" ;) I guess it should be rather "common Jenkins libs and scripts"

---
*[a discussion](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MYtkhrO4zYjD7Jxdcyz:-MYtkhrO4zYjD7Jxdcz-:bgypykq) (no related file):*
I believe you can un-draft this PR

---
___
*[jenkins/lib/api.groovy, line 31 at r7](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MYnTj_85Qwggh7nYKF6:-MYtjqfq7y-teZXfZBZY:b-zcjvte) ([raw file](https://github.com/pmem/dev-utils-kit/blob/66935e7d9b55448180718fd0dc0a840c9f1bc56a/jenkins/lib/api.groovy#L31)):*
<details><summary><i>Previously, tszczyp (Tomasz Szczypiorowski) wrote…</i></summary><blockquote>

Updated.
</blockquote></details>

Thanks
___
*[jenkins/lib/api.groovy, line 147 at r8](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MYtjwti-3gggEsreRNS:-MYtjwti-3gggEsreRNT:b-r1zrqv) ([raw file](https://github.com/pmem/dev-utils-kit/blob/6be1e9d8fc5d29e999b3060331b4134faf98f44c/jenkins/lib/api.groovy#L147)):*
> ```Groovy
> 
> /**
>  * Add repository revision to known revisions. This is used for example to send e-mail with test result.
> ```

pls update the comment - "known revisions" is now renamed
___
*[jenkins/lib/api.groovy, line 224 at r8](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MYtkIzv93qsPRy2wGwA:-MYtkIzv93qsPRy2wGwB:bau764o) ([raw file](https://github.com/pmem/dev-utils-kit/blob/6be1e9d8fc5d29e999b3060331b4134faf98f44c/jenkins/lib/api.groovy#L224)):*
> ```Groovy
> 	dir(target_directory) {
> 		run_bash_script("git log --oneline -n 5")
> 		if (keep_sha) {
> ```

hmm this `if` could be above this `dir{}` clause, not inside of it
___
*[jenkins/scripts/createNamespace.sh, line 92 at r8](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MYtk_RH0lQmgmdsgVTF:-MYtk_RH0lQmgmdsgVTG:b-26dbmq) ([raw file](https://github.com/pmem/dev-utils-kit/blob/6be1e9d8fc5d29e999b3060331b4134faf98f44c/jenkins/scripts/createNamespace.sh#L92)):*
> ```Shell
> 
> if $CREATE_PMEM; then
>   echo "Creating fsdax namespace"
> ```

there are spaces instead of a tab (to indent the line)


<!-- Sent from Reviewable.io -->

2021-04-23 10:15 UTC, tszczyp reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1)* status: 4 of 6 files reviewed, 9 unresolved discussions (waiting on @lukaszstolarczuk, @nedved1, and @tszczyp)

*[a discussion](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MWP6u0d1Dl59jHGSa8O:-MYyDOVJ5lUrPkmdKzeY:b-jfelv4) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

it says "pmemkv libs and scripts" ;) I guess it should be rather "common Jenkins libs and scripts"
</blockquote></details>

Changed. :)

---
___
*[jenkins/lib/api.groovy, line 147 at r8](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MYtjwti-3gggEsreRNS:-MYyDIsA6buVr_EeksW6:b-896fix) ([raw file](https://github.com/pmem/dev-utils-kit/blob/6be1e9d8fc5d29e999b3060331b4134faf98f44c/jenkins/lib/api.groovy#L147)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls update the comment - "known revisions" is now renamed
</blockquote></details>

Done.
___
*[jenkins/lib/api.groovy, line 224 at r8](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MYtkIzv93qsPRy2wGwA:-MYyDJzF1VxwNz4bgIQh:b-896fix) ([raw file](https://github.com/pmem/dev-utils-kit/blob/6be1e9d8fc5d29e999b3060331b4134faf98f44c/jenkins/lib/api.groovy#L224)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

hmm this `if` could be above this `dir{}` clause, not inside of it
</blockquote></details>

Done.
___
*[jenkins/scripts/createNamespace.sh, line 92 at r8](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MYtk_RH0lQmgmdsgVTF:-MYyDL3p3pnTmHXgd4cf:bt2vr1b) ([raw file](https://github.com/pmem/dev-utils-kit/blob/6be1e9d8fc5d29e999b3060331b4134faf98f44c/jenkins/scripts/createNamespace.sh#L92)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

there are spaces instead of a tab (to indent the line)
</blockquote></details>

Fixed.


<!-- Sent from Reviewable.io -->

2021-04-23 10:36 UTC, lukaszstolarczuk reviewed
> Reviewed 2 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1)* status: all files reviewed, 6 unresolved discussions (waiting on @nedved1 and @tszczyp)

*[a discussion](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MYtkhrO4zYjD7Jxdcyz:-MYyIG4cELS9VvFwcql7:bxi7qll) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I believe you can un-draft this PR
</blockquote></details>

and pls update the PR title

---
___
*[jenkins/scripts/createNamespace.sh, line 92 at r8](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MYtk_RH0lQmgmdsgVTF:-MYyI4Px-NY67k0cZCnC:b14t8ra) ([raw file](https://github.com/pmem/dev-utils-kit/blob/6be1e9d8fc5d29e999b3060331b4134faf98f44c/jenkins/scripts/createNamespace.sh#L92)):*
<details><summary><i>Previously, tszczyp (Tomasz Szczypiorowski) wrote…</i></summary><blockquote>

Fixed.
</blockquote></details>

not done, still spaces, instead of tab (now here and below) - other lines above use tabs, so pls align


<!-- Sent from Reviewable.io -->

2021-04-27 09:53 UTC, tszczyp reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1)* status: 5 of 6 files reviewed, 6 unresolved discussions (waiting on @lukaszstolarczuk and @nedved1)

*[a discussion](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MYtkhrO4zYjD7Jxdcyz:-MZHjoKj3A4ZhWyDmk2S:b-bu91xm) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

and pls update the PR title
</blockquote></details>

Updated

---
___
*[jenkins/scripts/createNamespace.sh, line 92 at r8](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MYtk_RH0lQmgmdsgVTF:-MZHjIZU8-569Q8rPfJT:b-obhf6o) ([raw file](https://github.com/pmem/dev-utils-kit/blob/6be1e9d8fc5d29e999b3060331b4134faf98f44c/jenkins/scripts/createNamespace.sh#L92)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

not done, still spaces, instead of tab (now here and below) - other lines above use tabs, so pls align
</blockquote></details>

Now there are tabs on 100% :D


<!-- Sent from Reviewable.io -->

2021-04-27 12:44 UTC, nedved1 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1)* status: 5 of 6 files reviewed, 3 unresolved discussions (waiting on @lukaszstolarczuk and @tszczyp)

___
*[jenkins/lib/api.groovy, line 10 at r10](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZILasdDFqF2klUCRgh:-MZILaseEeOpGS38NcZ2:b-cfy03o) ([raw file](https://github.com/pmem/dev-utils-kit/blob/460336ae9d2e2f3e5fc2333cbcc0d7ffbc69b071/jenkins/lib/api.groovy#L10)):*
> ```Groovy
> /* declarations of common paths and filenames: */
> 
> /* do not change to "${...}" - it's required to use ' due to expansion on OS's shell */
> ```

you can delete this comment now.


<!-- Sent from Reviewable.io -->

2021-04-27 12:54 UTC, lukaszstolarczuk reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-:-MZIOJuA5Z0dtYyWFnfR:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @tszczyp)

___
*[jenkins/scripts/createNamespace.sh, line 92 at r8](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MYtk_RH0lQmgmdsgVTF:-MZIOD-8-ot_964vwY5P:b-jw2irv) ([raw file](https://github.com/pmem/dev-utils-kit/blob/6be1e9d8fc5d29e999b3060331b4134faf98f44c/jenkins/scripts/createNamespace.sh#L92)):*
<details><summary><i>Previously, tszczyp (Tomasz Szczypiorowski) wrote…</i></summary><blockquote>

Now there are tabs on 100% :D
</blockquote></details>

tabs For The Win ;)


<!-- Sent from Reviewable.io -->

2021-04-27 13:10 UTC, nedved1 reviewed
> Reviewed 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1)* status: all files reviewed, 2 unresolved discussions (waiting on @tszczyp)

___
*[jenkins/scripts/createNamespace.sh, line 119 at r10](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZIRRnGAMs7-1g0diuF:-MZIRRnGAMs7-1g0diuG:b-hwtska) ([raw file](https://github.com/pmem/dev-utils-kit/blob/460336ae9d2e2f3e5fc2333cbcc0d7ffbc69b071/jenkins/scripts/createNamespace.sh#L119)):*
> ```Shell
> 
> echo "Print created namespaces:"
> ndctl list -X | jq -r '.[] | select(.mode=="devdax") | [.daxregion.devices[].chardev, "align: "+(.daxregion.align/1024|tostring+"k"), "size: "+(.size/1024/1024/1024|tostring+"G") ]'
> ```

Unfortunately this syntax can no longer work on some newer distributions and newer versions of ndctl please change it to
`ndctl list -X | jq -r '.[] | select(.mode=="devdax") | [.daxregion.devices[].chardev, "align: "+(.align/1024|tostring+"k"), "size: "+(.size/1024/1024/1024|tostring+"G") ]'
`


<!-- Sent from Reviewable.io -->

2021-04-28 09:52 UTC, tszczyp reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk and @nedved1)

___
*[jenkins/lib/api.groovy, line 10 at r10](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZILasdDFqF2klUCRgh:-MZMt3BN0gx4V7zuR0sL:b-896fix) ([raw file](https://github.com/pmem/dev-utils-kit/blob/460336ae9d2e2f3e5fc2333cbcc0d7ffbc69b071/jenkins/lib/api.groovy#L10)):*
<details><summary><i>Previously, nedved1 (Pawel Niedzwiecki) wrote…</i></summary><blockquote>

you can delete this comment now.
</blockquote></details>

Done.
___
*[jenkins/scripts/createNamespace.sh, line 119 at r10](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZIRRnGAMs7-1g0diuF:-MZMt4IDCawe3OfmHnAy:b-896fix) ([raw file](https://github.com/pmem/dev-utils-kit/blob/460336ae9d2e2f3e5fc2333cbcc0d7ffbc69b071/jenkins/scripts/createNamespace.sh#L119)):*
<details><summary><i>Previously, nedved1 (Pawel Niedzwiecki) wrote…</i></summary><blockquote>

Unfortunately this syntax can no longer work on some newer distributions and newer versions of ndctl please change it to
`ndctl list -X | jq -r '.[] | select(.mode=="devdax") | [.daxregion.devices[].chardev, "align: "+(.align/1024|tostring+"k"), "size: "+(.size/1024/1024/1024|tostring+"G") ]'
`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-28 09:53 UTC, nedved1 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk, @nedved1, and @tszczyp)

___
*[jenkins/lib/api.groovy, line 10 at r10](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZILasdDFqF2klUCRgh:-MZMtTtp40pdqwSwUy2s:b2nid0f) ([raw file](https://github.com/pmem/dev-utils-kit/blob/460336ae9d2e2f3e5fc2333cbcc0d7ffbc69b071/jenkins/lib/api.groovy#L10)):*
<details><summary><i>Previously, tszczyp (Tomasz Szczypiorowski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

thx
___
*[jenkins/scripts/createNamespace.sh, line 119 at r10](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZIRRnGAMs7-1g0diuF:-MZMtR3v7tqsq1kJBIV0:b2nid0f) ([raw file](https://github.com/pmem/dev-utils-kit/blob/460336ae9d2e2f3e5fc2333cbcc0d7ffbc69b071/jenkins/scripts/createNamespace.sh#L119)):*
<details><summary><i>Previously, tszczyp (Tomasz Szczypiorowski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

thx


<!-- Sent from Reviewable.io -->

2021-04-28 09:54 UTC, nedved1 reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-:-MZMt_FZBtdnqeTv-Zae:bnfp4nl)* status: 4 of 6 files reviewed, all discussions resolved (waiting on @lukaszstolarczuk and @nedved1)



<!-- Sent from Reviewable.io -->

2021-04-28 11:29 UTC, KFilipek reviewed
> Reviewed 1 of 6 files at r1, 1 of 4 files at r2, 1 of 3 files at r3, 1 of 3 files at r8, 2 of 2 files at r11.
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1)* status: all files reviewed, 3 unresolved discussions (waiting on @tszczyp)

___
*[README.md, line 4 at r11](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZN9qBDE7qYFNRfE97F:-MZN9qBDE7qYFNRfE97G:bqsphb3) ([raw file](https://github.com/pmem/dev-utils-kit/blob/893c6438ca2fc21484848cc10b1752ae15470eeb/README.md#L4)):*
> ```Markdown
> 
> ## Overview
> The content of this repository consist of scripts and functions meant to be used within other repositories.
> ```

consists
___
*[jenkins/README.md, line 47 at r11](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZN9mD13Z5Eha5AxxXN:-MZN9mD13Z5Eha5AxxXO:b-p01zky) ([raw file](https://github.com/pmem/dev-utils-kit/blob/893c6438ca2fc21484848cc10b1752ae15470eeb/jenkins/README.md#L47)):*
> ```Markdown
> ## Managing Jenkins
> 
> ### Overivew
> ```

Overview
___
*[jenkins/lib/api.groovy, line 101 at r11](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZNBz1bA4IT7eOg1wr9:-MZNBz1bA4IT7eOg1wrA:bf1dw9h) ([raw file](https://github.com/pmem/dev-utils-kit/blob/893c6438ca2fc21484848cc10b1752ae15470eeb/jenkins/lib/api.groovy#L101)):*
> ```
>  Runs
> ```
extra space
___
*[jenkins/scripts/common.sh, line 67 at r11](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZNCjHk5PE8o1q2oY0F:-MZNCjHl3wjNfCu_Mp8-:b-u9ifia) ([raw file](https://github.com/pmem/dev-utils-kit/blob/893c6438ca2fc21484848cc10b1752ae15470eeb/jenkins/scripts/common.sh#L67)):*
<details><summary><i alt="summary">Quoted 13 lines of code…</i></summary>

> ```
>  ___            ___
> /   \          /   \                            HELLO!
> \_   \        /  __/            THIS NODE IS CONNECTED TO PMEM ORIENTED JENKINS
>  _\   \      /  /__             THERE ARE TESTS CURRENTLY RUNNING ON THIS MACHINE
>  \___  \____/   __/                         PLEASE GO AWAY :)
>      \_       _/
>        | @ @  \_
>        |                        FOR MORE INFORMATION GO: ${info_addr}
>      _/     /\
>     /o)  (o/\ \_
>     \_____/ /
>       \____/
> EOL"
> ```
</details>

xD


<!-- Sent from Reviewable.io -->

2021-04-28 12:15 UTC, nedved1 reviewed
> Reviewed 2 of 2 files at r11.
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1)* status: all files reviewed, 3 unresolved discussions (waiting on @tszczyp)



<!-- Sent from Reviewable.io -->

2021-04-28 12:54 UTC, mramotowski commented
___
*[jenkins/README.md, line 85 at r11](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZNWiqxDokyWadJqLBr:-MZNWiqyBQDXQOcZAA3f:b-12xnst) ([raw file](https://github.com/pmem/dev-utils-kit/blob/893c6438ca2fc21484848cc10b1752ae15470eeb/jenkins/README.md#L85)):*
> ```Markdown
> 
> ### In-process Script Approval
> By default, Jenkins will prevent to run new groovy scrips which will cause our job to fail. After each fail caused by an unapproved script, it is needed to accept this script. Unfortunately, this will be necessary to repeat several times, by launching this job repeatedly (only after creating this job, for the first time).
> ```

I think you meant scripts not scrips.


<!-- Sent from Reviewable.io -->

2021-04-28 13:23 UTC, tszczyp reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1)* status: 3 of 6 files reviewed, 4 unresolved discussions (waiting on @KFilipek, @lukaszstolarczuk, @mramotowski, and @nedved1)

___
*[README.md, line 4 at r11](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZN9qBDE7qYFNRfE97F:-MZNd9eHEwA8Ch4vDJgn:b-896fix) ([raw file](https://github.com/pmem/dev-utils-kit/blob/893c6438ca2fc21484848cc10b1752ae15470eeb/README.md#L4)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

consists
</blockquote></details>

Done.
___
*[jenkins/README.md, line 47 at r11](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZN9mD13Z5Eha5AxxXN:-MZNdFJU5y80c-OsqfjW:b-a2ujfl) ([raw file](https://github.com/pmem/dev-utils-kit/blob/893c6438ca2fc21484848cc10b1752ae15470eeb/jenkins/README.md#L47)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Overview
</blockquote></details>

Changed.
___
*[jenkins/README.md, line 85 at r11](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZNWiqxDokyWadJqLBr:-MZNdHNB3UGN67Cl6q2i:b-6ldl4l) ([raw file](https://github.com/pmem/dev-utils-kit/blob/893c6438ca2fc21484848cc10b1752ae15470eeb/jenkins/README.md#L85)):*
<details><summary><i>Previously, mramotowski wrote…</i></summary><blockquote>

I think you meant scripts not scrips.
</blockquote></details>

Yes indeed.
___
*[jenkins/lib/api.groovy, line 101 at r11](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZNBz1bA4IT7eOg1wr9:-MZNdSKT8zVcE0ollDxM:bnxx097) ([raw file](https://github.com/pmem/dev-utils-kit/blob/893c6438ca2fc21484848cc10b1752ae15470eeb/jenkins/lib/api.groovy#L101)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> ```
>  Runs
> ```
extra space
</blockquote></details>

It's gone.


<!-- Sent from Reviewable.io -->

2021-04-28 13:38 UTC, mramotowski commented
___
*[jenkins/lib/api.groovy, line 50 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZNfyzJ0zTeKozd9LpA:-MZNfyzJ0zTeKozd9LpB:bi6o757) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/lib/api.groovy#L50)):*
> ```Groovy
>  * @return object with 'output' field, containing command's output, and 'status' with its returned code.
>  */
> def run_bash_script(script_text, log_file = LOG_FILE, import_common_file = false, error_on_non_zero_rc = true) {
> ```

Just a question. Why do you extend Jenkins api instead of writing your own scripts for this? I mean if you ever need to change CI/CD tool to another you will need to reimplement logic wrote here. Wouldn't it be better to write for example Python script that does it and just call it in Jenkins sh block? 


<!-- Sent from Reviewable.io -->

2021-04-28 23:25 UTC, janekmi requested changes
> Reviewed 2 of 3 files at r12.
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1)* status: 5 of 6 files reviewed, 53 unresolved discussions (waiting on @KFilipek, @mramotowski, @nedved1, and @tszczyp)

___
*[jenkins/README.md, line 4 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPfM9w5-g1cVsaWLgy:-MZPfM9w5-g1cVsaWLgz:bfkpq53) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/README.md#L4)):*
> ```Markdown
> 
> ## Overview
> This directory contains shared functions and scripts meant to be used with jenkins pipelines. Jenkinsfile and pipeline are required beforehand to start a job.
> ```

Do 'Jenkinsfile' lack space between one another?
___
*[jenkins/README.md, line 9 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPfcti1p3O8hleg4Hy:-MZPfcti1p3O8hleg4Hz:bxcrf9v) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/README.md#L9)):*
> ```Markdown
> 
> ### Overview
> Jenkins is a self contained, open sourced automation server which can be used to automate tasks related to building and testing. Its functionality can be expanded by installing plugins.
> ```

`self-contained`
___
*[jenkins/README.md, line 9 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPfpw86RXeo6mLhRFC:-MZPfpw86RXeo6mLhRFD:b-uqybx3) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/README.md#L9)):*
> ```Markdown
> 
> ### Overview
> Jenkins is a self contained, open sourced automation server which can be used to automate tasks related to building and testing. Its functionality can be expanded by installing plugins.
> ```

`which can be used to` -> `that can`
___
*[jenkins/README.md, line 9 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPh_Y-4x_VwoRx7K5x:-MZPh_Y-4x_VwoRx7K5y:b4jpcwf) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/README.md#L9)):*
> ```Markdown
> 
> ### Overview
> Jenkins is a self contained, open sourced automation server which can be used to automate tasks related to building and testing. Its functionality can be expanded by installing plugins.
> ```

I would like to have here a link to the place I can really get Jenkins.
___
*[jenkins/README.md, line 11 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPgDw36HhdBDn7231-:-MZPgDw36HhdBDn72310:b-v7so7x) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/README.md#L11)):*
> ```Markdown
> Jenkins is a self contained, open sourced automation server which can be used to automate tasks related to building and testing. Its functionality can be expanded by installing plugins.
> 
> Jenkins main function is to launch jobs. Jobs are scripts that cover managing repositories, building and testing. Jenkins pipeline is a script that is launched by Jenkins job. Each pipeline consists of build stages that follow one another, for example: download repository, build, test, etc. Each stage consists of steps that are actual commands ran on an actual device under test - which is called: Node.
> ```

`... an actual device under test - which is called: Node.` -> `... an actual device under a test called 'Node'.`
___
*[jenkins/README.md, line 11 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPgUxUDDtmB2CPzlGl:-MZPgUxUDDtmB2CPzlGm:b235h2j) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/README.md#L11)):*
> ```Markdown
> Jenkins is a self contained, open sourced automation server which can be used to automate tasks related to building and testing. Its functionality can be expanded by installing plugins.
> 
> Jenkins main function is to launch jobs. Jobs are scripts that cover managing repositories, building and testing. Jenkins pipeline is a script that is launched by Jenkins job. Each pipeline consists of build stages that follow one another, for example: download repository, build, test, etc. Each stage consists of steps that are actual commands ran on an actual device under test - which is called: Node.
> ```

`Each stage consists of steps that are actual commands ran on...` -> `Each stage consists of actual commands that run on...`
___
*[jenkins/README.md, line 43 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPgfQN0421HpMlTy5f:-MZPgfQN0421HpMlTy5g:bi51gg) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/README.md#L43)):*
> ```Markdown
> - SSH Agent
> - SSH Build Agents
> - Timestamper
> ```

Whoa. Seriously all of them are required just to start?
___
*[jenkins/README.md, line 45 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPlBOQ6c2H8MKEP62Y:-MZPlBOQ6c2H8MKEP62Z:bt2fn6j) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/README.md#L45)):*
> ```Markdown
> - Timestamper
> 
> ## Managing Jenkins
> ```

I'm just curious, these steps are not described in the Jenkins documentation?
Can we just give a link instead of writing all of these by our selves?
___
*[jenkins/README.md, line 48 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPgsKm8w2-jDiwVnM3:-MZPgsKm8w2-jDiwVnM4:bpbms7m) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/README.md#L48)):*
> ```Markdown
> 
> ### Overview
> Jenkins can be configured and managed "as a code" - it means that actual jobs and pipelines can be downloaded from remote repository. But first it is needed to add a job that downloads jobs definitions from remote repository and configures Jenkins. Instructions below allows to manually trigger creating/updating jobs, but it is possible to trigger this job automatically with each push to target repository.
> ```

...and pipelines can be downloaded from **a** remote repository.
___
*[jenkins/README.md, line 48 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPgw900vt2K7Wi1c3o:-MZPgw900vt2K7Wi1c3p:bsl2rg) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/README.md#L48)):*
> ```Markdown
> 
> ### Overview
> Jenkins can be configured and managed "as a code" - it means that actual jobs and pipelines can be downloaded from remote repository. But first it is needed to add a job that downloads jobs definitions from remote repository and configures Jenkins. Instructions below allows to manually trigger creating/updating jobs, but it is possible to trigger this job automatically with each push to target repository.
> ```

`But first, ...`
___
*[jenkins/README.md, line 48 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPhFya2eK0QbSiUN4V:-MZPhFya2eK0QbSiUN4W:b-cf4cdg) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/README.md#L48)):*
> ```Markdown
> 
> ### Overview
> Jenkins can be configured and managed "as a code" - it means that actual jobs and pipelines can be downloaded from remote repository. But first it is needed to add a job that downloads jobs definitions from remote repository and configures Jenkins. Instructions below allows to manually trigger creating/updating jobs, but it is possible to trigger this job automatically with each push to target repository.
> ```

...that downloads jobs definitions from **the** remote repository and configures...
___
*[jenkins/README.md, line 48 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPhNFEB0EVoR3ytq_6:-MZPhNFEB0EVoR3ytq_7:bqo9y2u) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/README.md#L48)):*
> ```Markdown
> 
> ### Overview
> Jenkins can be configured and managed "as a code" - it means that actual jobs and pipelines can be downloaded from remote repository. But first it is needed to add a job that downloads  [...]

2021-04-28 23:27 UTC, janekmi requested changes
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1)* status: 5 of 6 files reviewed, 57 unresolved discussions (waiting on @KFilipek, @mramotowski, @nedved1, and @tszczyp)

___
*[jenkins/scripts/removeNamespaces.sh, line 11 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPnWNs1jBMYpLPUUAU:-MZPnWNs1jBMYpLPUUAV:bbpk4q7) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/removeNamespaces.sh#L11)):*
> ```Shell
> 
> echo "Clearing all existing namespaces"
> sudo umount $MOUNT_POINT || true
> ```

You expect it to fail?
What is the role of `|| true`?
___
*[jenkins/scripts/removeNamespaces.sh, line 19 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPnmeI8oYLY97_QPfV:-MZPnmeI8oYLY97_QPfW:b6a81od) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/removeNamespaces.sh#L19)):*
> ```Shell
> 	sudo ndctl clear-errors $n -v
> done
> sudo ndctl disable-namespace all || true
> ```

You are missing a new line here.
___
*[jenkins/scripts/removeNamespaces.sh, line 19 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPnqLvE4N92gXl_bWX:-MZPnqLvE4N92gXl_bWY:buwr0ze) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/removeNamespaces.sh#L19)):*
> ```Shell
> 	sudo ndctl clear-errors $n -v
> done
> sudo ndctl disable-namespace all || true
> ```

What is the role of `|| true`?
___
*[jenkins/scripts/removeNamespaces.sh, line 20 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPnpxi8dz7aNaiL9qj:-MZPnpxi8dz7aNaiL9qk:buwr0ze) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/removeNamespaces.sh#L20)):*
> ```Shell
> done
> sudo ndctl disable-namespace all || true
> sudo ndctl destroy-namespace all || true
> ```

What is the role of `|| true`?


<!-- Sent from Reviewable.io -->

2021-04-28 23:51 UTC, janekmi requested changes
> Reviewed 1 of 2 files at r11.
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1)* status: 5 of 6 files reviewed, 83 unresolved discussions (waiting on @KFilipek, @mramotowski, @nedved1, and @tszczyp)

___
*[jenkins/scripts/createNamespace.sh, line 10 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPoAUpCQoVZLgGcdY5:-MZPoAUpCQoVZLgGcdY6:bnd0qtd) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/createNamespace.sh#L10)):*
> ```Shell
> 
> # region used for dax namespaces.
> DEV_DAX_R=0x0000
> ```

You are introducing a magic number. I would like to see a comment describing where it comes from.
___
*[jenkins/scripts/createNamespace.sh, line 12 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPoL0o44yn49al5enU:-MZPoL0o44yn49al5enV:b-i961cv) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/createNamespace.sh#L12)):*
> ```Shell
> DEV_DAX_R=0x0000
> # region used for fsdax namespaces.
> FS_DAX_R=0x0001
> ```

magic number
___
*[jenkins/scripts/createNamespace.sh, line 16 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPozXO9nbEZT0lo8As:-MZPozXO9nbEZT0lo8At:b-nj0g93) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/createNamespace.sh#L16)):*
> ```Shell
> CREATE_PMEM=false
> MOUNT_POINT="/mnt/pmem0"
> SIZE=100G
> ```

If it is a default would it be good to have `DEFAULT` somewhere here?
Without reading the `usage()` I would not know it is used as default by simply reading its definition.
___
*[jenkins/scripts/createNamespace.sh, line 20 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPoRX6-bcmsWSzwabJ:-MZPoRX6-bcmsWSzwabK:b-86qkew) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/createNamespace.sh#L20)):*
> ```Shell
> function usage()
> {
> 	echo ""
> ```

`echo` is enough.
___
*[jenkins/scripts/createNamespace.sh, line 21 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPobH020IkE6yf2X4m:-MZPobH020IkE6yf2X4n:buw6gct) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/createNamespace.sh#L21)):*
> ```Shell
> {
> 	echo ""
> 	echo "Script for creating namespaces, mountpoint, and configuring file permissions."
> ```

`mount point`?
___
*[jenkins/scripts/createNamespace.sh, line 21 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPplcB4dDYfkaAjeJR:-MZPplcB4dDYfkaAjeJS:bybief3) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/createNamespace.sh#L21)):*
> ```Shell
> {
> 	echo ""
> 	echo "Script for creating namespaces, mountpoint, and configuring file permissions."
> ```

Do you mean "creating mount points"?
I am missing a verb here.
___
*[jenkins/scripts/createNamespace.sh, line 24 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPokmh53hjbkwgVjOa:-MZPokmh53hjbkwgVjOb:bfu6z02) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/createNamespace.sh#L24)):*
> ```Shell
> 	echo "Usage: $(basename $1) [-h|--help]  [-d|--dax] [-p|--pmem] [--size]"
> 	echo "-h, --help       Print help and exit"
> 	echo "-d, --dax        Create dax device."
> ```

Please remove this full stop.
___
*[jenkins/scripts/createNamespace.sh, line 25 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPooihCfCCV8r2r1Fa:-MZPooihCfCCV8r2r1Fb:b-cxncrl) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/createNamespace.sh#L25)):*
> ```Shell
> 	echo "-h, --help       Print help and exit"
> 	echo "-d, --dax        Create dax device."
> 	echo "-p, --pmem       Create fsdax device and create mountpoint."
> ```

~~the full stop~~
___
*[jenkins/scripts/createNamespace.sh, line 31 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPpUyB3L96BBNxXm_F:-MZPpUyB3L96BBNxXm_G:b-adfj5s) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/createNamespace.sh#L31)):*
> ```Shell
> function clear_namespaces() {
> 	scriptdir=$(readlink -f $(dirname ${BASH_SOURCE[0]}))
> 	$scriptdir/removeNamespaces.sh
> ```

clear, remove. Is it possible to use the same naming convention all the way?
___
*[jenkins/scripts/createNamespace.sh, line 39 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPpztaDq15PYXqZJcX:-MZPpztaDq15PYXqZJcY:bkafbd1) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/createNamespace.sh#L39)):*
> ```Shell
> 	local size=$2
> 	local cmd="sudo ndctl create-namespace --mode devdax -a ${align} -s ${size} -r ${DEV_DAX_R} -f"
> 	result=$(${cmd})
> ```

I'm not sure whether this intermediate variable makes anything simpler.
___
*[jenkins/scripts/createNamespace.sh, line 41 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPq7s-8n8Sgw5BkvxO:-MZPq7s-8n8Sgw5BkvxP:b-w9msah) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/createNamespace.sh#L41)):*
> ```Shell
> 	result=$(${cmd})
> 	if [ $? -ne 0 ]; then
> 		exit 1;
> ```

It seems `;` is redundant here.
___
*[jenkins/scripts/createNamespace.sh, line 49 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPqSEQ2XL_9eKf4bFc:-MZPqSEQ2XL_9eKf4bFd:b8pmw0a) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/createNamespace.sh#L49)):*
> ```Shell
> 	local size=$1
> 	local cmd="sudo ndctl create-namespace --mode fsdax -s ${size} -r ${FS_DAX_R} -f"
> 	result=$(${cmd})
> ```

Do you really need this intermediate?
___
*[jenkins/scripts/createNamespace.sh, line 51 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPqVvv3kSQhWQhhgAm:-MZPqVvv3kSQhWQhhgAn:b1eonl8) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/createNamespace.sh#L51)):*
> ```Shell
> 	result=$(${cmd})
> 	if [ $? -ne 0 ]; then
> 		exit 1;
> ```

`;` not needed.
___
*[jenkins/scripts/createNamespace.sh, line 74 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPqomi7mIb_uZZmOjK:-MZPqomi7mIb_uZZmOjL:b66s33y) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/createNamespace.sh#L74)):*
> ```Shell
> done
> 
> # There is no default test cofiguration in this script. Configurations has to be specified.
> ```

There is no default test configuration in this script. Configurations have to be specified.
___
*[jenkins/scripts/createNamespace.sh, line 76 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPrYD608KQ346Iht35:-MZPrYD608KQ346Iht36:b-tpmn9c) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/createNamespace.sh#L76)):*
> ```Shell
> # There is no default test cofiguration in this script. Configurations has to be specified.
> if ! $CREATE_DAX && ! $CREATE_PMEM; then
> 	echo ""
> ```

`echo`
___
*[jenkins/scripts/createNamespace.sh, line 77 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPrgS4CJmXQwRvB5sA:-MZPrgS4CJmXQwRvB5sB:bbjoup) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/createNamespace.sh#L77)):*
> ```Shell
> if ! $CREATE_DAX && ! $CREATE_PMEM; then
> 	echo ""
> 	echo "ERROR: No config type selected. Please select one or more config types."
> ```

Either `config` or `configuration`. Apply consequently.
___
*[jenkins/scripts/createNamespace.sh, line 85 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPs9Tn9FPnIk-QNPMz:-MZPs9Tn9FPnIk-QNPN-:b-mt3376) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1 [...]

2021-04-28 23:57 UTC, janekmi requested changes
> Reviewed 1 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1)* status: 5 of 6 files reviewed, 91 unresolved discussions (waiting on @KFilipek, @mramotowski, @nedved1, and @tszczyp)

___
*[jenkins/scripts/common.sh, line 12 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPu1tl7RyuurF4jsxh:-MZPu1tl7RyuurF4jsxi:b-gqjdbq) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/common.sh#L12)):*
> ```Shell
> 
> function system_info {
> 	echo "********** system-info **********"
> ```

Either ` system-info ` or `system-info`. Apply consistently.
___
*[jenkins/scripts/common.sh, line 19 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPthImDvctxuNJ8Dmd:-MZPthImDvctxuNJ8Dme:bptv6aa) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/common.sh#L19)):*
> ```Shell
> 	echo "libpmem: $(pkg-config --modversion libpmem || echo 'libpmem not found')"
> 	echo "libpmemobj: $(pkg-config --modversion libpmemobj || echo 'libpmemobj not found')"
> 	echo "libpmemobj++: $(pkg-config --modversion libpmemobj++ || echo 'libpmemobj++ not found')"
> ```

Where is librpma? :sob: 
___
*[jenkins/scripts/common.sh, line 24 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPtoeq7BHMOj9aMr3u:-MZPtoeq7BHMOj9aMr3v:b-2qutus) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/common.sh#L24)):*
> ```Shell
> 	echo "TBB : $(pkg-config --modversion TBB || echo 'TBB not found')"
> 	echo "valgrind: $(pkg-config --modversion valgrind || echo 'valgrind not found')"
> 	echo "**********memory-info**********"
> ```

Does it look fine without empty lines before each section?
___
*[jenkins/scripts/common.sh, line 26 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPtzN69R-vTEgpB2Y7:-MZPtzN69R-vTEgpB2Y8:bve6yfg) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/common.sh#L26)):*
> ```Shell
> 	echo "**********memory-info**********"
> 	sudo ipmctl show -dimm || true
> 	sudo ipmctl show -topology || true
> ```

`|| true` ?
___
*[jenkins/scripts/common.sh, line 32 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPu9P0Bsj4sUgbT5Nr:-MZPu9P0Bsj4sUgbT5Ns:bve6yfg) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/common.sh#L32)):*
> ```Shell
> 	zypper se --installed-only 2>/dev/null || true
> 	apt list --installed 2>/dev/null || true
> 	yum list installed 2>/dev/null || true
> ```

`|| true` ?
___
*[jenkins/scripts/common.sh, line 47 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPuGY19ty9YB-fnJe0:-MZPuGY19ty9YB-fnJe1:b-3datlh) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/common.sh#L47)):*
> ```Shell
> 	echo "**********check-updates**********"
> 	sudo zypper list-updates 2>/dev/null || true
> 	sudo apt-get update 2>/dev/null || true ; apt upgrade --dry-run 2>/dev/null || true
> ```

Why these two are together?
___
*[jenkins/scripts/common.sh, line 73 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPuQTl4PeMzlnonxLR:-MZPuQTl4PeMzlnonxLS:bve6yfg) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/common.sh#L73)):*
> ```Shell
> 
> function disable_warning_message {
> 	sudo rm /etc/motd || true
> ```

`|| true` ?
___
*[jenkins/scripts/common.sh, line 76 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPuWM-0YuoJS4B1zA4:-MZPuWM-0YuoJS4B1zA5:b-2yglzd) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/common.sh#L76)):*
> ```Shell
> }
> 
> # Check host linux distribution and return distro name 
> ```

Linux

Show some respect. ;-)


<!-- Sent from Reviewable.io -->

2021-04-29 00:32 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1)* status: 5 of 6 files reviewed, 139 unresolved discussions (waiting on @KFilipek, @mramotowski, @nedved1, and @tszczyp)

___
*[jenkins/lib/api.groovy, line 28 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPuvjV7iYoz3pHrpaa:-MZPuvjV7iYoz3pHrpab:bq6t9lr) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/lib/api.groovy#L28)):*
> ```Groovy
> REVISION_FILENAME = "sha.txt"
> ```

Too many new lines.
___
*[jenkins/lib/api.groovy, line 29 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPv17o0FAl04wB_4U7:-MZPv17o0FAl04wB_4U8:b-uad22m) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/lib/api.groovy#L29)):*
> ```Groovy
> 
> 
> /* List of git revisions used in a job. It should contain list of dicts (with 'url' and 'sha' keys) */
> ```

a list
___
*[jenkins/lib/api.groovy, line 32 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPv6740sWwnDewPxJM:-MZPv6740sWwnDewPxJN:bhiu4dl) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/lib/api.groovy#L32)):*
> ```Groovy
> saved_git_revisions = []
> 
> /* interpolation function for log absolute filepath */
> ```

What are you interpolating here?
___
*[jenkins/lib/api.groovy, line 35 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPvBkK9-6pu-e63CsY:-MZPvBkK9-6pu-e63CsZ:b-un2b6y) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/lib/api.groovy#L35)):*
> ```Groovy
> def abs_logfile_path() {
> 	return "${WORKSPACE}/${OUTPUT_DIR_NAME}/${LOG_FILENAME}"
> }
> ```

A new line is missing.
___
*[jenkins/lib/api.groovy, line 38 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPvMb93DsgFNeDL3cA:-MZPvMb93DsgFNeDL3cB:b9ebynh) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/lib/api.groovy#L38)):*
> ```Groovy
> /* low-level functions for basic interaction with OS on the DUT: */
> 
> /* Required to use top-level function inside class method */
> ```

a class method
___
*[jenkins/lib/api.groovy, line 42 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPvYot9JUdipEfnOi0:-MZPvYot9JUdipEfnOi1:bt3ki5m) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/lib/api.groovy#L42)):*
> ```Groovy
> 
> /**
>  * Runs a script in bash and logs its output.
> ```

`Run` or `Runs`. When decided apply consistently.
___
*[jenkins/lib/api.groovy, line 50 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZNfyzJ0zTeKozd9LpA:-MZPwMFQ5GhqsywHP7Zz:b-bxrcmn) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/lib/api.groovy#L50)):*
<details><summary><i>Previously, mramotowski wrote…</i></summary><blockquote>

Just a question. Why do you extend Jenkins api instead of writing your own scripts for this? I mean if you ever need to change CI/CD tool to another you will need to reimplement logic wrote here. Wouldn't it be better to write for example Python script that does it and just call it in Jenkins sh block? 
</blockquote></details>

From my side is completely not just a question. It is awful to generating scripts on the fly.
If it is completely doable just as @mramotowski said, what is the point?
___
*[jenkins/lib/api.groovy, line 54 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPwpKy0aSbi9x7r1kT:-MZPwpKy0aSbi9x7r1kU:b-grudek) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/lib/api.groovy#L54)):*
> ```Groovy
> 	first, prepare optional portions of the script:
> 	redirect all script's output to the files:
> 	1. Separate log file for this current command exclusively, with random name.
> ```

a random name
___
*[jenkins/lib/api.groovy, line 55 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPx5rx3vh1O05MTtrG:-MZPx5rx3vh1O05MTtrH:bke7549) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/lib/api.groovy#L55)):*
> ```Groovy
> 	redirect all script's output to the files:
> 	1. Separate log file for this current command exclusively, with random name.
> 	2. If requested - append to given log file.
> ```

the given
___
*[jenkins/lib/api.groovy, line 56 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPwrZl1FEvNAvo9JdL:-MZPwrZl1FEvNAvo9JdM:b-mq1232) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/lib/api.groovy#L56)):*
> ```Groovy
> 	1. Separate log file for this current command exclusively, with random name.
> 	2. If requested - append to given log file.
> 	*/
> ```

You either comment like this:

````
/*
 * xxx
 */
```

or like this:

```
/*
xxx
*/
```

Up to you.
___
*[jenkins/lib/api.groovy, line 69 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPxFyh5AcK5AMKIonV:-MZPxFyh5AcK5AMKIonW:b-ce45hf) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/lib/api.groovy#L69)):*
> ```Groovy
> 	"""
> 
> 	/* import things defined in common.sh file if not set otherwise: */
> ```

You either add a full stop or a colon or nothing. So far they are all over the place at random.
___
*[jenkins/lib/api.groovy, line 79 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPx_xM6sBAxlZfh0ce:-MZPx_xM6sBAxlZfh0cf:bock7t2) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/lib/api.groovy#L79)):*
> ```Groovy
> 		${script_text}
> 	"""
> 	/* second, do the actual call: */
> ```

The new line is missing.
___
*[jenkins/lib/api.groovy, line 82 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPxjD06dQBeS79OE1V:-MZPxjD06dQBeS79OE1W:b-ho8fg0) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/lib/api.groovy#L82)):*
> ```Groovy
> 	def returned_status = sh(script: full_script_body, returnStatus: true)
> 
> 	/* third, capture script output from file: */
> ```

the file
___
*[jenkins/lib/api.groovy, line 82 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPxlfX4J3Km3HbEJsW:-MZPxlfX4J3Km3HbEJsX:b-7s4ubq) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/lib/api.groovy#L82)):*
> ```Groovy
> 	def returned_status = sh(script: full_script_body, returnStatus: true)
> 
> 	/* third, capture script output from file: */
> ```

colon
___
*[jenkins/lib/api.groovy, line 85 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPxmh4CAuwMs8TfQdj:-MZPxmh4CAuwMs8TfQdk:b-7s4ubq) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/lib/api.groovy#L85)):*
> ```Groovy
> 	def script_output = readFile current_script_output_file
> 
> 	/* delete the log file: */
> ```

colon
___
*[jenkins/lib/api.groovy, line 113 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPyEcbE1Z7ZPx3pavG:-MZPyEcbE1Z7ZPx3pavH:b-9v5eg7) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/lib/api.groovy#L113)):*
> ```Groovy
> /**
>  * Runs CMake script, with parameters and extra env vars, if needed.
>  * @param path A path pointing to directory with CMakeLists.txt file.
> ```

the directory
___
*[jenkins/lib/api.groovy, line 121 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPyIJr1FTT2d3YIp9f:-MZPyIJr1FTT2d3YIp9g:b-un2b6y) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/lib/api.groovy#L121)):*
> ```Groovy
> 		additional_env_vars = "export ${additional_env_vars} &&"
> 	}
> 	run_bash_script("${additional_env_vars} cmake ${path} ${parameters}")
> ```

A new line is missing.
___
*[jenkins/lib [...]

2021-04-29 00:41 UTC, janekmi requested changes
> Reviewed 1 of 3 files at r12.
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1)* status: all files reviewed, 151 unresolved discussions (waiting on @KFilipek, @mramotowski, and @tszczyp)

___
*[jenkins/lib/api.groovy, line 339 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZQ1oYu3YFXoTjSqGq3:-MZQ1oYu3YFXoTjSqGq4:b-73vojk) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/lib/api.groovy#L339)):*
> ```Groovy
> 		writeFile file: "${result}.txt", text: result
> 	}
> 	archiveArtifacts artifacts: "${RESULTS_DIR_NAME}/*.*"
> ```

artefacts
___
*[jenkins/lib/api.groovy, line 355 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZQ1y-I8iaxYfTvUW-t:-MZQ1y-I8iaxYfTvUW-u:b-azhoki) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/lib/api.groovy#L355)):*
> ```Groovy
> 
> /**
>  * Get week number of date when current build has started.
> ```

Get the week number of the date when the current build has started.
___
*[jenkins/lib/api.groovy, line 360 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZQ20Sg-XIVDuWPBu6v:-MZQ20Sg-XIVDuWPBu6w:bo5iez) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/lib/api.groovy#L360)):*
> ```Groovy
> def get_work_week_of_build_start() {
> 	/* 
> 	Groovy sandbox does not allow to change properties of locale, default start of the week is on Sunday,
> ```

Default of the host OS which you know nothing about or something more solid?
___
*[jenkins/lib/api.groovy, line 361 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZQ2Y7P79iHCg6nrRsQ:-MZQ2Y7P79iHCg6nrRsR:b-f4f5ue) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/lib/api.groovy#L361)):*
> ```Groovy
> 	/* 
> 	Groovy sandbox does not allow to change properties of locale, default start of the week is on Sunday,
> 	so we need to make a trick: shift the starting date by one day ahead - this will give us in the result proper week
> ```

~~in~~
___
*[jenkins/lib/api.groovy, line 364 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZQ2bKL-lmNNGyNLbeY:-MZQ2bKL-lmNNGyNLbeZ:b-un66s3) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/lib/api.groovy#L364)):*
> ```Groovy
> 	number with starting on Monday.
> 
> 	roovy sandbox does not allow creation of Date objects with constructor different than Unix milliseconds epoch,
> ```

groovy 
___
*[jenkins/lib/api.groovy, line 364 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZQ2eHI2b9Ch-EIg5fF:-MZQ2eHI2b9Ch-EIg5fG:b-k3v1l9) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/lib/api.groovy#L364)):*
> ```Groovy
> 	number with starting on Monday.
> 
> 	roovy sandbox does not allow creation of Date objects with constructor different than Unix milliseconds epoch,
> ```

the creation
___
*[jenkins/lib/api.groovy, line 366 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZQ2iTWCOss-dloc6Dv:-MZQ2iTWCOss-dloc6Dw:b-7s4ubq) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/lib/api.groovy#L366)):*
> ```Groovy
> 	roovy sandbox does not allow creation of Date objects with constructor different than Unix milliseconds epoch,
> 	so we cannot count in days but only in milliseconds
> 	(24 hours / 1 day) * (60 minutes / 1 hour) * (60 seconds / 1 minute) * (1000 milliseconds / 1 second):
> ```

colon
___
*[jenkins/lib/api.groovy, line 367 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZQ2H3x3fYU2rb6NR7W:-MZQ2H3x3fYU2rb6NR7X:b-gok9j0) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/lib/api.groovy#L367)):*
> ```Groovy
> 	so we cannot count in days but only in milliseconds
> 	(24 hours / 1 day) * (60 minutes / 1 hour) * (60 seconds / 1 minute) * (1000 milliseconds / 1 second):
> 	*/
> ```

Please see my comment about the formatting of the comments.
___
*[jenkins/lib/api.groovy, line 370 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZQ2mGU-xKKmpe9nQXk:-MZQ2mGU-xKKmpe9nQXl:b-7s4ubq) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/lib/api.groovy#L370)):*
> ```Groovy
> 	def one_day_in_ms = 24 * 60 * 60 * 1000
> 
> 	/*  get build start date object: */
> ```

colon
___
*[jenkins/lib/api.groovy, line 373 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZQ2na6AkCtsU0aYJQ0:-MZQ2na6AkCtsU0aYJQ1:b-7s4ubq) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/lib/api.groovy#L373)):*
> ```Groovy
> 	def start_date = new Date(currentBuild.startTimeInMillis + one_day_in_ms)
> 
> 	/*  get week number and cast it to integer: */
> ```

colon
___
*[jenkins/lib/api.groovy, line 399 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZQ2vvU9j4wJ1SSadjp:-MZQ2vvU9j4wJ1SSadjq:b8kmxy2) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/lib/api.groovy#L399)):*
> ```Groovy
> 	def get_html_table_data_row() {
> 		def urls =
> 				"<a href=\"${env.JENKINS_URL}/blue/organizations/jenkins/${currentBuild.projectName}/detail/${currentBuild.projectName}/${currentBuild.id}/pipeline\">blue</a>, <a href=\"${env.JENKINS_URL}/blue/organizations/jenkins/${currentBuild.projectName}/detail/${currentBuild.projectName}/${currentBuild.id}/tests\">blue tests</a>, <a href=\"${env.JENKINS_URL}/view/all/job/${currentBuild.projectName}/${currentBuild.id}/testReport\">tests</a>, <a href=\"${env.JENKINS_URL}/view/all/job/${currentBuild.projectName}/${currentBuild.id}/\">build</a>, <a href=\"${env.JENKINS_URL}/view/all/job/${currentBuild.projectName}/${currentBuild.id}/consoleText\">console</a>, <a href=\"${env.JENKINS_URL}/job/${currentBuild.projectName}/${currentBuild.id}/artifact/results/system_info.txt\">system_info</a>"
> ```

Please format HTML like HTML should be formatted. Obfuscation is undesired in this situation.
___
*[jenkins/lib/api.groovy, line 449 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZQ3MtI9QFdjS1VXwah:-MZQ3MtI9QFdjS1VXwai:b-x95rwd) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/lib/api.groovy#L449)):*
> ```Groovy
>  * @param recipients Addressee of the mail.
>  */
> ```

A redundant new line.


<!-- Sent from Reviewable.io -->

2021-04-29 09:35 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1)* status: all files reviewed, 151 unresolved discussions (waiting on @janekmi, @KFilipek, @mramotowski, and @tszczyp)

___
*[jenkins/scripts/common.sh, line 3 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPlwcNCklmvWN1upM5:-MZRwbqU7nLg8RQj4bmg:b-a5agsw) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/common.sh#L3)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Is it open-sourced somewhere else for two years by now?
If it is not just 2021.
</blockquote></details>

it's been copied from pmem/pmemkv
___
*[jenkins/scripts/common.sh, line 19 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPthImDvctxuNJ8Dmd:-MZRvMAY7GIgeqZGhEuy:b5qhap1) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/common.sh#L19)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Where is librpma? :sob: 
</blockquote></details>

that's why we asked all for the review! :)

If this script will be used in all our Jenkins (rpma does have one?), pls extend the list with more libs, not only used by my team
___
*[jenkins/scripts/common.sh, line 24 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPtoeq7BHMOj9aMr3u:-MZRwEH7CELWk86-jw2i:b-bmwrgg) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/common.sh#L24)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Does it look fine without empty lines before each section?
</blockquote></details>

I've read these logs, they are as readable as possible, but a space wouldn't cost much ;)

and also, now I think we could extend this "**********" to be a bit longer, so it will be even better visible in the wall of logs
___
*[jenkins/scripts/common.sh, line 26 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPtzN69R-vTEgpB2Y7:-MZRw5GD2lTwbnnKH-U0:b-g25f48) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/common.sh#L26)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`|| true` ?
</blockquote></details>

we might run this on a machine without dimms ;) but good point, we could at least print something, like a big warning ;)
___
*[jenkins/scripts/common.sh, line 32 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPu9P0Bsj4sUgbT5Nr:-MZRxcvA-IKLf8zl-ao0:b-g7krle) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/common.sh#L32)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`|| true` ?
</blockquote></details>

not sure for all of these "trues" later on in the review, but here it's actually acceptable, since this handles different OSes..

we could have some checks for each distro, but it may become obsolete very fast
___
*[jenkins/scripts/createNamespace.sh, line 3 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPmUe76MlwU4FCmPGu:-MZRwoJI0YWgo-ez1R-a:b2y4xud) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/createNamespace.sh#L3)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

2021?
</blockquote></details>

. (it's OK)
___
*[jenkins/scripts/createNamespace.sh, line 85 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPs9Tn9FPnIk-QNPMz:-MZRxMmY7J2myhvJxmod:b-b6mtit) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/createNamespace.sh#L85)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Sophisticated. Do we really need such trickery?
</blockquote></details>

I vote for traps, they're cool and handle "exceptions"


<!-- Sent from Reviewable.io -->

2021-04-29 09:44 UTC, KFilipek reviewed
> Reviewed 3 of 3 files at r12.
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1)* status: all files reviewed, 148 unresolved discussions (waiting on @janekmi, @mramotowski, and @tszczyp)



<!-- Sent from Reviewable.io -->

2021-04-29 11:41 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1)* status: all files reviewed, 144 unresolved discussions (waiting on @lukaszstolarczuk, @mramotowski, and @tszczyp)

___
*[jenkins/scripts/common.sh, line 32 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPu9P0Bsj4sUgbT5Nr:-MZSOjxQ4l-mURYT2Qcv:bdicz8c) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/common.sh#L32)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

not sure for all of these "trues" later on in the review, but here it's actually acceptable, since this handles different OSes..

we could have some checks for each distro, but it may become obsolete very fast
</blockquote></details>

What if the distro has to package managers? Anyone is really reading these outputs? ;-)
___
*[jenkins/scripts/createNamespace.sh, line 85 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPs9Tn9FPnIk-QNPMz:-MZSP4FdDIBKKa_uLcmo:b-e3kau0) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/createNamespace.sh#L85)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I vote for traps, they're cool and handle "exceptions"
</blockquote></details>

Ok... I think I have understood what it is all about. Fine. Do you need to zero it out or it exists only within a subshell?


<!-- Sent from Reviewable.io -->

2021-04-29 11:54 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1)* status: all files reviewed, 144 unresolved discussions (waiting on @janekmi, @mramotowski, and @tszczyp)

___
*[jenkins/scripts/common.sh, line 32 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPu9P0Bsj4sUgbT5Nr:-MZST94M-ZznLg3CT6ks:b-4xu3k2) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/common.sh#L32)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

What if the distro has to package managers? Anyone is really reading these outputs? ;-)
</blockquote></details>

I don't think we can have such case on our machines, but if we'll do for some reason we'll just get more output ;)

I do read them sometime.. of course, when I need to check something (if something failed) :D


<!-- Sent from Reviewable.io -->

2021-04-30 12:01 UTC, tszczyp reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1)* status: 5 of 6 files reviewed, 144 unresolved discussions (waiting on @janekmi, @KFilipek, @mramotowski, and @tszczyp)

___
*[jenkins/README.md, line 4 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPfM9w5-g1cVsaWLgy:-MZXPWBz2-fNovIKD_ai:b-5wzjys) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/README.md#L4)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Do 'Jenkinsfile' lack space between one another?
</blockquote></details>

Not exactly, jenkinsfile is a name of the file, which is used along with jenkins pipelines. As stated in documentation:
![image.png](https://files.reviewableusercontent.io/images/reviewable/25879106/3xvdLRTOM1TtiHHx2m83mXzQ/image.png)
https://www.jenkins.io/doc/book/pipeline/jenkinsfile/
___
*[jenkins/README.md, line 9 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPfcti1p3O8hleg4Hy:-MZXStqEDabItbF2ZT-Z:b-896fix) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/README.md#L9)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`self-contained`
</blockquote></details>

Done.
___
*[jenkins/README.md, line 9 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPfpw86RXeo6mLhRFC:-MZXSuXn75lhiJYy_NgH:b-qiwf15) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/README.md#L9)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`which can be used to` -> `that can`
</blockquote></details>

I have to decline, mentioned change is equal in meaning in this context. If you insist, I can make that change but I don't find it necessary.
___
*[jenkins/README.md, line 9 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPh_Y-4x_VwoRx7K5x:-MZXU5n873PEsw-4FyXL:boyjfql) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/README.md#L9)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I would like to have here a link to the place I can really get Jenkins.
</blockquote></details>

This documentation shouldn't exactly show how to prepare a new jenkins instance, be it from docker or otherwise, but to guide already somewhat experienced users how to configure your already existing one, so I personally don't think it should contain this kind of links, but if you insist I can add one.
___
*[jenkins/README.md, line 11 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPgDw36HhdBDn7231-:-MZXWObc4M_Kn2EpBlJT:b-896fix) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/README.md#L11)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`... an actual device under test - which is called: Node.` -> `... an actual device under a test called 'Node'.`
</blockquote></details>

Done.
___
*[jenkins/README.md, line 11 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPgUxUDDtmB2CPzlGl:-MZXWQLd8n_HmYjaWdQN:b-u5l86v) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/README.md#L11)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`Each stage consists of steps that are actual commands ran on...` -> `Each stage consists of actual commands that run on...`
</blockquote></details>

I have to decline, as steps are responsible for running commands, not the stages themselves, thus l didn't change this line in a way you proposed, but I did delete one 'an actual' since I thought it looked better.
___
*[jenkins/README.md, line 43 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPgfQN0421HpMlTy5f:-MZXYhwLBmPKIDXYRGhV:b-r4xysj) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/README.md#L43)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Whoa. Seriously all of them are required just to start?
</blockquote></details>

Most of them are required to start, but a few of them are useful for security or graphical improvements, that's why they're recommended to have.
___
*[jenkins/README.md, line 45 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPlBOQ6c2H8MKEP62Y:-MZXZfNVAt87zkEFUwIk:b-aijomk) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/README.md#L45)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I'm just curious, these steps are not described in the Jenkins documentation?
Can we just give a link instead of writing all of these by our selves?
</blockquote></details>

This documentation is written in a more practical and easier to read kind of way, it contains exactly what you need to run jenkins jobs, nothing more, nothing less. It shouldn't describe how to prepare a new jenkins instance, but how to configure an already existing one.
___
*[jenkins/README.md, line 48 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPgsKm8w2-jDiwVnM3:-MZX_vQL4rLdm98wnEEH:b-896fix) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/README.md#L48)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

...and pipelines can be downloaded from **a** remote repository.
</blockquote></details>

Done.
___
*[jenkins/README.md, line 48 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPgw900vt2K7Wi1c3o:-MZX_x8eAavky-TCnJbI:b-896fix) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/README.md#L48)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`But first, ...`
</blockquote></details>

Done.
___
*[jenkins/README.md, line 48 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPhFya2eK0QbSiUN4V:-MZX_zOg8-RWGt25eqYp:b-896fix) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/README.md#L48)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

...that downloads jobs definitions from **the** remote repository and configures...
</blockquote></details>

Done.
___
*[jenkins/README.md, line 48 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPhNFEB0EVoR3ytq_6:-MZXa0gKCWvSCtrFcsJG:b-896fix) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/README.md#L48)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

The instructions below allow to...
</blockquote></details>

Done.
___
*[jenkins/README.md, line 48 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPhQ_fDVcLP-bTj7xz:-MZXa2sJ0ASamspm49CK:b-896fix) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/README.md#L48)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

...each push to **the** target repository.
</blockquote></details>

Done.
___
*[jenkins/README.md, line 51 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPhojw2XS5s5Wxguuw:-MZXaIRF-5lhqUFR0hKF:bpz9dvs) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/README.md#L51)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

which will run **the** Jenkins job.
</blockquote></details>

Change was required yes, but I think it should be 'a'
___
*[jenkins/README.md, line 51 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPht_U2FlHqWmXADc4: [...]

2021-05-06 09:17 UTC, KFilipek reviewed
> Reviewed 1 of 1 files at r13.
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1)* status: all files reviewed, 144 unresolved discussions (waiting on @janekmi, @mramotowski, and @tszczyp)

___
*[jenkins/lib/api.groovy, line 324 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZQ1eWs9Hrzo7mMBlQ4:-M_-xCcm4NtGnVudmirh:b-mn5xno) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/lib/api.groovy#L324)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

artefacts 
</blockquote></details>

https://www.dict.com/angielsko-polski/artefakt 
"artifact" is a British English
___
*[jenkins/lib/api.groovy, line 328 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZQ1fuD9wAWjbxZdlqY:-M_-xKL-EQDU2snz-Olo:b3kqx) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/lib/api.groovy#L328)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

artefacts 
</blockquote></details>

.
___
*[jenkins/scripts/common.sh, line 73 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPuQTl4PeMzlnonxLR:-M_-xdFaCj1bGfaCMB-s:bsd0t2x) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/common.sh#L73)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`|| true` ?
</blockquote></details>

https://unix.stackexchange.com/questions/325705/why-is-pattern-command-true-useful/325727
___
*[jenkins/scripts/common.sh, line 76 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPuWM-0YuoJS4B1zA4:-M_-xf1iAy2-bVmh0KHG:bfivhdq) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/common.sh#L76)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Linux

Show some respect. ;-)
</blockquote></details>

Linus can bite


<!-- Sent from Reviewable.io -->

2021-05-06 10:23 UTC, janekmi requested changes
> Reviewed 1 of 1 files at r13.
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1)* status: all files reviewed, 108 unresolved discussions (waiting on @janekmi, @mramotowski, and @tszczyp)

___
*[jenkins/README.md, line 9 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPfpw86RXeo6mLhRFC:-M_069N79FJtxXg8g08v:bdxgprt) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/README.md#L9)):*
<details><summary><i>Previously, tszczyp (Tomasz Szczypiorowski) wrote…</i></summary><blockquote>

I have to decline, mentioned change is equal in meaning in this context. If you insist, I can make that change but I don't find it necessary.
</blockquote></details>

It is equal in meaning but the current version is a lot longer and harder to follow. I do insist.
___
*[jenkins/README.md, line 9 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPh_Y-4x_VwoRx7K5x:-M_06lDm8Myeqfmuoua7:bpjqk01) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/README.md#L9)):*
<details><summary><i>Previously, tszczyp (Tomasz Szczypiorowski) wrote…</i></summary><blockquote>

This documentation shouldn't exactly show how to prepare a new jenkins instance, be it from docker or otherwise, but to guide already somewhat experienced users how to configure your already existing one, so I personally don't think it should contain this kind of links, but if you insist I can add one.
</blockquote></details>

If so I recommend putting assumptions/prerequisites at the beginning. On the other hand, if you assume the reader has experience in using Jenkins why you start from what Jenkins is?
___
*[jenkins/README.md, line 43 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPgfQN0421HpMlTy5f:-M_07wDGB0VGtG-MAM3F:bsskyif) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/README.md#L43)):*
<details><summary><i>Previously, tszczyp (Tomasz Szczypiorowski) wrote…</i></summary><blockquote>

Most of them are required to start, but a few of them are useful for security or graphical improvements, that's why they're recommended to have.
</blockquote></details>

So please put real requirements together whereas nice-to-haves separately as optional but recommended?
___
*[jenkins/README.md, line 51 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPiBX38WIMXoBZy0v2:-M_08of78wFVRA8sgS2D:b-q7tmfh) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/README.md#L51)):*
<details><summary><i>Previously, tszczyp (Tomasz Szczypiorowski) wrote…</i></summary><blockquote>

As above.
</blockquote></details>

I'm not a Jenkins guru. Is pipeline fully identified by the Jenkins job or it is somewhat separate so "a pipeline" here means "some pipeline will be but it is not yet decided which one"?
___
*[jenkins/README.md, line 97 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPiqo3BqwLMHsvVPEF:-M_0AFjZ0uBDNl1_k14_:bclxxfp) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/README.md#L97)):*
<details><summary><i>Previously, tszczyp (Tomasz Szczypiorowski) wrote…</i></summary><blockquote>

It should be 'a SSH server' afaik, but changed.
</blockquote></details>

English is somewhat misleading in this matter.

Ref:
- https://en.wikipedia.org/wiki/Comparison_of_SSH_servers
- https://en.wikipedia.org/wiki/Secure_Shell_Protocol
- https://www.digitalocean.com/community/tutorials/how-to-use-ssh-to-connect-to-a-remote-server
___
*[jenkins/README.md, line 124 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPjgHT8GZfRHmzjCQs:-M_0Ar_E4NNaWeXXdGuo:bpuqvxn) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/README.md#L124)):*
<details><summary><i>Previously, tszczyp (Tomasz Szczypiorowski) wrote…</i></summary><blockquote>

Actually it is written like this in a jenkins' node configuration
![image.png](https://files.reviewableusercontent.io/images/reviewable/25879106/RztyvPTUx1T3UAbG0DWwor08/image.png)

</blockquote></details>

I see. Put all of this into quotes, please.
___
*[jenkins/lib/api.groovy, line 324 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZQ1eWs9Hrzo7mMBlQ4:-M_0BsSHCo079Qg2v84u:b-vryuju) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/lib/api.groovy#L324)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

https://www.dict.com/angielsko-polski/artefakt 
"artifact" is a British English
</blockquote></details>

Oh, thank you. I didn't know that.


<!-- Sent from Reviewable.io -->

2021-05-06 10:31 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1)* status: all files reviewed, 108 unresolved discussions (waiting on @KFilipek, @lukaszstolarczuk, @mramotowski, and @tszczyp)

___
*[jenkins/scripts/common.sh, line 32 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPu9P0Bsj4sUgbT5Nr:-M_0CyVd1DSH64Tn2eE3:b-u1yi8v) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/common.sh#L32)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I don't think we can have such case on our machines, but if we'll do for some reason we'll just get more output ;)

I do read them sometime.. of course, when I need to check something (if something failed) :D
</blockquote></details>

Ok. So, if it is a workaround to easily support various distribution please just put a comment on why we are doing it this way.
___
*[jenkins/scripts/common.sh, line 73 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPuQTl4PeMzlnonxLR:-M_0DY5nAJ-3g7cSSSm4:b-o8bydn) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/common.sh#L73)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

https://unix.stackexchange.com/questions/325705/why-is-pattern-command-true-useful/325727
</blockquote></details>

I got it. But it should be an exception and in my opinion, every use of this technique requires a good comment describing why you expect this command to fail and why it is ok.
___
*[jenkins/scripts/common.sh, line 76 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPuWM-0YuoJS4B1zA4:-M_0DrZk0Rtla9uetSp5:b32vin) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/common.sh#L76)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Linus can bite
</blockquote></details>

:D


<!-- Sent from Reviewable.io -->

2021-05-18 06:56 UTC, lukaszstolarczuk commented
@tszczyp, ping, any update here? It looks like the review is going the right way and it'd be great to finally finish this task up :)

2021-05-21 13:18 UTC, tszczyp reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1)* status: 4 of 6 files reviewed, 108 unresolved discussions (waiting on @janekmi, @KFilipek, @lukaszstolarczuk, @mramotowski, and @tszczyp)

___
*[jenkins/README.md, line 9 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPfpw86RXeo6mLhRFC:-MaDnO8p2UKbFCablmnP:b-xc3v73) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/README.md#L9)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It is equal in meaning but the current version is a lot longer and harder to follow. I do insist.
</blockquote></details>

Sure, it's done.
___
*[jenkins/README.md, line 43 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPgfQN0421HpMlTy5f:-MaDnwyF9_V8O_w7T4St:b-896fix) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/README.md#L43)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

So please put real requirements together whereas nice-to-haves separately as optional but recommended?
</blockquote></details>

Done.
___
*[jenkins/README.md, line 51 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPiBX38WIMXoBZy0v2:-MaDoIjjCMrA_EKyHI96:b-okdm87) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/README.md#L51)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I'm not a Jenkins guru. Is pipeline fully identified by the Jenkins job or it is somewhat separate so "a pipeline" here means "some pipeline will be but it is not yet decided which one"?
</blockquote></details>

Yes, usually there is one pipeline assigned to one or more jenkins jobs, you were right in this context, so it's changed.
___
*[jenkins/README.md, line 97 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPiqo3BqwLMHsvVPEF:-MaDr9-F8hwRHWY143d7:b-nbpttq) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/README.md#L97)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

English is somewhat misleading in this matter.

Ref:
- https://en.wikipedia.org/wiki/Comparison_of_SSH_servers
- https://en.wikipedia.org/wiki/Secure_Shell_Protocol
- https://www.digitalocean.com/community/tutorials/how-to-use-ssh-to-connect-to-a-remote-server
</blockquote></details>

Well that was unexpected, changed.
___
*[jenkins/README.md, line 124 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPjgHT8GZfRHmzjCQs:-MaDrFqf4XYNOLvCYFWj:b-896fix) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/README.md#L124)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I see. Put all of this into quotes, please.
</blockquote></details>

Done.
___
*[jenkins/lib/api.groovy, line 4 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPlFg8436Scpqt5J8u:-MaDrHQUDVU5U1Tye_ap:b-896fix) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/lib/api.groovy#L4)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Either make it a sentence or do not use the full stop at the end.
</blockquote></details>

Done.
___
*[jenkins/lib/api.groovy, line 28 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPuvjV7iYoz3pHrpaa:-MaDrIz7-F4esKS50xOT:b-896fix) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/lib/api.groovy#L28)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Too many new lines.
</blockquote></details>

Done.
___
*[jenkins/lib/api.groovy, line 29 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPv17o0FAl04wB_4U7:-MaDrJXdCe7o-ntFZMyh:b-896fix) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/lib/api.groovy#L29)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

a list
</blockquote></details>

Done.
___
*[jenkins/lib/api.groovy, line 32 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPv6740sWwnDewPxJM:-MaDs42zABAmq1cI3lXu:bc83vx0) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/lib/api.groovy#L32)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

What are you interpolating here?
</blockquote></details>

As written in the comment, interpolation is used to return an absolute path to log files, I don't exactly know what more I can say about this :D
___
*[jenkins/lib/api.groovy, line 35 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPvBkK9-6pu-e63CsY:-MaDrMb7BHkAuAeYMf3q:b-896fix) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/lib/api.groovy#L35)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

A new line is missing.
</blockquote></details>

Done.
___
*[jenkins/lib/api.groovy, line 38 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPvMb93DsgFNeDL3cA:-MaDu-Uk2ZfeYWC6yEwC:b-896fix) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/lib/api.groovy#L38)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

a class method
</blockquote></details>

Done.
___
*[jenkins/lib/api.groovy, line 42 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPvYot9JUdipEfnOi0:-MaDuU8p646MYiN2CTHN:bihboh6) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/lib/api.groovy#L42)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`Run` or `Runs`. When decided apply consistently.
</blockquote></details>

Can you please elaborate what do you mean exactly, ``Runs`` is used consistently in the comments
___
*[jenkins/lib/api.groovy, line 54 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPwpKy0aSbi9x7r1kT:-MaDvVISAxvk6krgqrHo:b-896fix) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/lib/api.groovy#L54)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

a random name
</blockquote></details>

Done.
___
*[jenkins/lib/api.groovy, line 55 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPx5rx3vh1O05MTtrG:-MaDvVkcA4UsyW88f4Ca:b-896fix) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/lib/api.groovy#L55)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

the given
</blockquote></details>

Done.
___
*[jenkins/lib/api.groovy, line 56 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPwrZl1FEvNAvo9JdL:-MaDvWaG0hDw-V5xejlC:b-n2lp3e) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/lib/api.groovy#L56)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You either comment like this:

````
/*
 * xxx
 */
```

or like this:

```
/*
xxx
*/
```

Up to you.
</blockquote></details>

Applied one method everywhere in the current file
___
*[jenkins/lib/api.groovy, line 69 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPxFyh5AcK5AMKIonV:-MaDvqqB3GogfDsHF6XH:bl149jr) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/lib/api.groovy#L69)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You either add a full stop or a colon or nothing. [...]

2021-05-24 14:49 UTC, tszczyp reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1)* status: 4 of 6 files reviewed, 108 unresolved discussions (waiting on @janekmi, @KFilipek, @mramotowski, and @tszczyp)

___
*[jenkins/scripts/common.sh, line 26 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPtzN69R-vTEgpB2Y7:-MaTalOi-nkxua1hNAA5:b5hqga1) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/common.sh#L26)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

we might run this on a machine without dimms ;) but good point, we could at least print something, like a big warning ;)
</blockquote></details>

An entire output from these commands is visible in the logs, including situations where there are no dimms in the platform, so personally I don't find it really necessary to add additional warning, unless it's something you think will be useful here, then sure, I can add a warning of some sort.
___
*[jenkins/scripts/common.sh, line 32 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPu9P0Bsj4sUgbT5Nr:-MaTcjWt2cGtdG1g0-Zj:b-o8pjdm) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/common.sh#L32)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Ok. So, if it is a workaround to easily support various distribution please just put a comment on why we are doing it this way.
</blockquote></details>

As mentioned, it is used to handle different systems. Since they're using a different package managers , we're doing this to ignore potential errors that may come along the way, that's all.
___
*[jenkins/scripts/common.sh, line 47 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPuGY19ty9YB-fnJe0:-MaTgi4fEcNliU1jZV6d:b-v26z0y) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/common.sh#L47)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Why these two are together?
</blockquote></details>

I don't know how to answer that question, since I'm not an original author of this file, if it looks wrong I can separate them.
___
*[jenkins/scripts/common.sh, line 73 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPuQTl4PeMzlnonxLR:-MaTi13AEz5-auWQfoIW:bdqqoll) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/common.sh#L73)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I got it. But it should be an exception and in my opinion, every use of this technique requires a good comment describing why you expect this command to fail and why it is ok.
</blockquote></details>

I can agree that a comment may be useful here, but I don't think it's necessary everywhere, their main purpose is to raise an easy to handle errors which can be ignored instead of something that may cause more issues.
___
*[jenkins/scripts/createNamespace.sh, line 21 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPobH020IkE6yf2X4m:-MaTmZsY6Kcr5a8OHz0k:b-x7pltw) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/createNamespace.sh#L21)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`mount point`?
</blockquote></details>

This is not a typo, it's a part of 'mount' command as shown below
![image.png](https://files.reviewableusercontent.io/images/reviewable/25879106/Cxc2xiYBuV4paMmDmClr64Ts/image.png)

https://man7.org/linux/man-pages/man8/mount.8.html
___
*[jenkins/scripts/createNamespace.sh, line 21 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPplcB4dDYfkaAjeJR:-MaTnO6t41OyJk7qE0o9:bribihm) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/createNamespace.sh#L21)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Do you mean "creating mount points"?
I am missing a verb here.
</blockquote></details>

As above.
___
*[jenkins/scripts/createNamespace.sh, line 39 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPpztaDq15PYXqZJcX:-MaTnX5BBl0TMAhXYV3g:b-qco5lc) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/createNamespace.sh#L39)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I'm not sure whether this intermediate variable makes anything simpler.
</blockquote></details>

This is quite useful actually, first we check if namespace creation command doesn't return any errors, then we're using its output to filter the name of newly created devdax.
___
*[jenkins/scripts/createNamespace.sh, line 49 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPqSEQ2XL_9eKf4bFc:-MaToirp2fw4upFAm4Go:bribihm) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/createNamespace.sh#L49)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Do you really need this intermediate?
</blockquote></details>

As above.
___
*[jenkins/scripts/createNamespace.sh, line 85 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPs9Tn9FPnIk-QNPMz:-MaToudD-BitkXCl1H4J:b-bjmwmf) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/createNamespace.sh#L85)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Ok... I think I have understood what it is all about. Fine. Do you need to zero it out or it exists only within a subshell?
</blockquote></details>

The idea is to 'clean' after itself after an error occurs or if the user cancels the script manually, so basically it leave no trails anyway.
___
*[jenkins/scripts/createNamespace.sh, line 97 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPs_Gh8upC1N4-AKDt:-MaTqDE0DW6RK05rObb3:b2nreh6) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/createNamespace.sh#L97)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Trickery.
</blockquote></details>

Same as above.


<!-- Sent from Reviewable.io -->

2021-05-25 10:42 UTC, tszczyp reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1)* status: 2 of 7 files reviewed, 108 unresolved discussions (waiting on @janekmi, @KFilipek, @lukaszstolarczuk, @mramotowski, @nedved1, and @tszczyp)

___
*[jenkins/scripts/common.sh, line 2 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPmGuSA9bHFx7uGiN2:-MaY-Ol4DgzXqCCjez3n:b-dwutwy) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/common.sh#L2)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This repository lacks a LICENSE file so SPDX licensing is no complete.
</blockquote></details>

Added LICENSE file.
___
*[jenkins/scripts/common.sh, line 5 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPmntYCvqQsdo314Oc:-MaY-U4d6nKNzoKj7Rkr:b-cmu8ta) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/common.sh#L5)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Is it a sentence so it ends up with the full stop?
</blockquote></details>

Yes it is a sentence, changed first letter to capital.
___
*[jenkins/scripts/common.sh, line 12 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPu1tl7RyuurF4jsxh:-MaY-pBV2BNV1qhZVMI0:b-896fix) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/common.sh#L12)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Either ` system-info ` or `system-info`. Apply consistently.
</blockquote></details>

Done.
___
*[jenkins/scripts/common.sh, line 19 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPthImDvctxuNJ8Dmd:-MaY-poT9lEQsf1P6S-B:bjxmz2r) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/common.sh#L19)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

that's why we asked all for the review! :)

If this script will be used in all our Jenkins (rpma does have one?), pls extend the list with more libs, not only used by my team
</blockquote></details>

Librpma added. If there is a need to add more libs, let me know which ones.
___
*[jenkins/scripts/common.sh, line 24 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPtoeq7BHMOj9aMr3u:-MaY06rk35ILnHx_jGK5:b-q1t67k) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/common.sh#L24)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I've read these logs, they are as readable as possible, but a space wouldn't cost much ;)

and also, now I think we could extend this "**********" to be a bit longer, so it will be even better visible in the wall of logs
</blockquote></details>

Line updated, as well as a few more.
___
*[jenkins/scripts/common.sh, line 76 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPuWM-0YuoJS4B1zA4:-MaY0Kr01UAtGtAm4sSH:b-896fix) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/common.sh#L76)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

:D
</blockquote></details>

Done.
___
*[jenkins/scripts/createNamespace.sh, line 5 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPmYeH8b5q3Ied-B9C:-MaY0icxEUJT-QQDe3t3:baq3bdn) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/createNamespace.sh#L5)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please format comments consistently. They either start from the big letter or they do not. ;-)
</blockquote></details>

Well it does start from the Capital letter, at least the proper sentence, ``createNamespace.sh`` is the name of the file after all.
___
*[jenkins/scripts/createNamespace.sh, line 9 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPn3Ee7JLDQ_6BCbL7:-MaY13885grkx3jXGYKO:bw8h3oi) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/createNamespace.sh#L9)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Is it a sentence?
</blockquote></details>

Yes it is a sentence, updated for the comment below as well.
___
*[jenkins/scripts/createNamespace.sh, line 10 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPoAUpCQoVZLgGcdY5:-MaY1CX03n-KgupERjrD:b-hmyog4) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/createNamespace.sh#L10)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You are introducing a magic number. I would like to see a comment describing where it comes from.
</blockquote></details>

Changes were made.
___
*[jenkins/scripts/createNamespace.sh, line 11 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPn0Wt73Ys2gc1lUmh:-MaY1Enr8omuTflVmbRd:bribihm) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/createNamespace.sh#L11)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Is it a sentence?
</blockquote></details>

As above.
___
*[jenkins/scripts/createNamespace.sh, line 12 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPoL0o44yn49al5enU:-MaY1FtR2wcj_hpqIydG:bribihm) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/createNamespace.sh#L12)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

magic number
</blockquote></details>

As above.
___
*[jenkins/scripts/createNamespace.sh, line 16 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPozXO9nbEZT0lo8As:-MaY1Iff1eAhQ59f4hRJ:b67pax5) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/createNamespace.sh#L16)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

If it is a default would it be good to have `DEFAULT` somewhere here?
Without reading the `usage()` I would not know it is used as default by simply reading its definition.
</blockquote></details>

Added comment above variable.
___
*[jenkins/scripts/createNamespace.sh, line 20 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPoRX6-bcmsWSzwabJ:-MaY1jkm7wCh7chiBE2U:b-896fix) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/createNamespace.sh#L20)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`echo` is enough.
</blockquote></details>

Done.
___
*[jenkins/scripts/createNamespace.sh, line 24 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPokmh53hjbkwgVjOa:-MaY1n4l52dVBbsfysE7:b-896fix) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/createNamespace.sh#L24)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please remove this full stop.
</blockquote></details>

Done.
___
*[jenkins/scripts/createNamespace.sh, line 25 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPooihCfCCV8r2r1Fa:-MaY1nQp98K_vTeozdzQ:b-896fix) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/createNamespace.sh#L25)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

~~the full stop~~
</blockquote></details>

Done.
___
*[jenkins/scripts/createNamespace.sh, line 31 at r12](https://reviewable.io/reviews/pmem/de [...]

2021-05-25 12:18 UTC, tszczyp reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1)* status: 1 of 7 files reviewed, 108 unresolved discussions (waiting on @janekmi, @KFilipek, @lukaszstolarczuk, @mramotowski, @nedved1, and @tszczyp)

___
*[jenkins/scripts/removeNamespaces.sh, line 5 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPn9zyCThCV_LsYYhu:-MaYQkB115JwJQ6d9fQW:b-gwiria) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/removeNamespaces.sh#L5)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Is it a sentence?
</blockquote></details>

Yes, yes it is.
___
*[jenkins/scripts/removeNamespaces.sh, line 11 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPnWNs1jBMYpLPUUAU:-MaYQqaoBntDGXVIULF0:b-73e1iu) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/removeNamespaces.sh#L11)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You expect it to fail?
What is the role of `|| true`?
</blockquote></details>

This command will return an error if for some reason mountpoint isn't available.
___
*[jenkins/scripts/removeNamespaces.sh, line 16 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPqw-s878wkG-F449e:-MaYRou9-4STp3fOK902:b-896fix) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/removeNamespaces.sh#L16)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You either do like this:

```sh
for i in j; do
```

```sh
for i in j
do
```

Up to you. Just please apply it consistently. Note it also includes `if x; then` etc.
</blockquote></details>

Done.
___
*[jenkins/scripts/removeNamespaces.sh, line 19 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPnmeI8oYLY97_QPfV:-MaYRpYG8PZq5fEmVVT_:b-896fix) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/removeNamespaces.sh#L19)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You are missing a new line here.
</blockquote></details>

Done.
___
*[jenkins/scripts/removeNamespaces.sh, line 19 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPnqLvE4N92gXl_bWX:-MaYRqBG5DomxU_fe_3L:b-gtmhny) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/removeNamespaces.sh#L19)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

What is the role of `|| true`?
</blockquote></details>

Just like in other cases, we are allowing singular commands to fail, to prevent a failure of an entire execution.
___
*[jenkins/scripts/removeNamespaces.sh, line 20 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPnpxi8dz7aNaiL9qj:-MaYSIfYD_Z2gip4ih35:bribihm) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/removeNamespaces.sh#L20)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

What is the role of `|| true`?
</blockquote></details>

As above.


<!-- Sent from Reviewable.io -->

2021-05-25 12:19 UTC, tszczyp reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1)* status: 1 of 7 files reviewed, 108 unresolved discussions (waiting on @janekmi, @KFilipek, @lukaszstolarczuk, @mramotowski, @nedved1, and @tszczyp)

___
*[jenkins/lib/api.groovy, line 212 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZQ-puTBB3TuAed6eoH:-MaYSmKPDDQYfqlwINTq:b-896fix) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/lib/api.groovy#L212)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

the current
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-25 14:29 UTC, nedved1 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1)* status: 1 of 7 files reviewed, 108 unresolved discussions (waiting on @janekmi, @KFilipek, @lukaszstolarczuk, @mramotowski, @nedved1, and @tszczyp)

___
*[jenkins/README.md, line 9 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPh_Y-4x_VwoRx7K5x:-MaYpHAE0N_KB5uNgwHA:baezn69) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/README.md#L9)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

If so I recommend putting assumptions/prerequisites at the beginning. On the other hand, if you assume the reader has experience in using Jenkins why you start from what Jenkins is?
</blockquote></details>

The fastest and the simplest way to get jenkins is to download docker file https://hub.docker.com/r/jenkins/jenkins/ an install it following docker/jenkins instructions https://github.com/jenkinsci/docker/blob/master/README.md maybe we could agree to put these links to readme? @janekmi 
___
*[jenkins/lib/api.groovy, line 50 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZNfyzJ0zTeKozd9LpA:-MaYq6451CWTWD33RTJ-:b-h17tg8) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/lib/api.groovy#L50)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

From my side is completely not just a question. It is awful to generating scripts on the fly.
If it is completely doable just as @mramotowski said, what is the point?
</blockquote></details>

Jenkins api isn't that very useful in some cases. For example it's not possible to extract exit code and output string at the same time using only jenkins 'sh' command :p so Python script would not give anything. For the other hand Jenkins allows running groovy scripts within its instance.
___
*[jenkins/lib/api.groovy, line 360 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZQ20Sg-XIVDuWPBu6v:-MaYsp0NCQMehSieuEc1:b-v8m9z1) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/lib/api.groovy#L360)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Default of the host OS which you know nothing about or something more solid?
</blockquote></details>

Default on the jenkins instance.


<!-- Sent from Reviewable.io -->

2021-05-25 14:42 UTC, KFilipek reviewed
> Reviewed 6 of 6 files at r14.
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1)* status: all files reviewed, 109 unresolved discussions (waiting on @janekmi, @mramotowski, and @tszczyp)

___
*[LICENSE, line 2 at r14](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MaYv6Uf7UcTHBWSGkqX:-MaYv6Uf7UcTHBWSGkqY:b-pg227o) ([raw file](https://github.com/pmem/dev-utils-kit/blob/b16cb29f92bcca5a1eaeb1e5691cbcf50106c227/LICENSE#L2)):*
> ```
> SPDX-License-Identifier: BSD-3-Clause
> Copyright 2014-2021, Intel Corporation
> ```

If is it new repo I would prefer '2021' only
___
*[jenkins/scripts/createNamespace.sh, line 21 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPobH020IkE6yf2X4m:-MaYyBB_3HAH7rWkDYOC:b382pco) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/createNamespace.sh#L21)):*
<details><summary><i>Previously, tszczyp (Tomasz Szczypiorowski) wrote…</i></summary><blockquote>

This is not a typo, it's a part of 'mount' command as shown below
![image.png](https://files.reviewableusercontent.io/images/reviewable/25879106/Cxc2xiYBuV4paMmDmClr64Ts/image.png)

https://man7.org/linux/man-pages/man8/mount.8.html
</blockquote></details>

@tszczyp +1


<!-- Sent from Reviewable.io -->

2021-05-26 08:13 UTC, janekmi requested changes
> Reviewed 4 of 6 files at r14.
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1)* status: all files reviewed, 38 unresolved discussions (waiting on @janekmi, @KFilipek, @lukaszstolarczuk, @mramotowski, @nedved1, and @tszczyp)

___
*[jenkins/README.md, line 9 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPh_Y-4x_VwoRx7K5x:-MabXjiA9NAS0ZYz6b4J:b-df2oea) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/README.md#L9)):*
<details><summary><i>Previously, nedved1 (Pawel Niedzwiecki) wrote…</i></summary><blockquote>

The fastest and the simplest way to get jenkins is to download docker file https://hub.docker.com/r/jenkins/jenkins/ an install it following docker/jenkins instructions https://github.com/jenkinsci/docker/blob/master/README.md maybe we could agree to put these links to readme? @janekmi 
</blockquote></details>

I think it is a good idea.
___
*[jenkins/lib/api.groovy, line 32 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPv6740sWwnDewPxJM:-MabYSUn0RkaQU1chSwV:b-jxspe9) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/lib/api.groovy#L32)):*
<details><summary><i>Previously, tszczyp (Tomasz Szczypiorowski) wrote…</i></summary><blockquote>

As written in the comment, interpolation is used to return an absolute path to log files, I don't exactly know what more I can say about this :D
</blockquote></details>

You are making an absolute path from a relative one. I do not know what interpolation means in this context.
___
*[jenkins/lib/api.groovy, line 42 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPvYot9JUdipEfnOi0:-MabZE7X36QALc9OFClK:b-v5lq9r) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/lib/api.groovy#L42)):*
<details><summary><i>Previously, tszczyp (Tomasz Szczypiorowski) wrote…</i></summary><blockquote>

Can you please elaborate what do you mean exactly, ``Runs`` is used consistently in the comments
</blockquote></details>

The form is not used consistently. You use both forms. The third-person singular (e.g. runs) and the basic (e.g. return, add).
___
*[jenkins/lib/api.groovy, line 28 at r14](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MabYJp7A36CJ28m7MR8:-MabYJp7A36CJ28m7MR9:bcq6vv4) ([raw file](https://github.com/pmem/dev-utils-kit/blob/b16cb29f92bcca5a1eaeb1e5691cbcf50106c227/jenkins/lib/api.groovy#L28)):*
> ```Groovy
> REVISION_FILENAME = "sha.txt"
> 
> /* A list of git revisions used in a job. It should contain list of dicts (with 'url' and 'sha' keys) */
> ```

Missing '.' at the end.
___
*[jenkins/lib/api.groovy, line 38 at r14](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MabYkZD1sj4D_20ZtAM:-MabYkZD1sj4D_20ZtAN:b-q5eepd) ([raw file](https://github.com/pmem/dev-utils-kit/blob/b16cb29f92bcca5a1eaeb1e5691cbcf50106c227/jenkins/lib/api.groovy#L38)):*
> ```Groovy
> /* low-level functions for basic interaction with OS on the DUT: */
> 
> /* Required to use top-level function inside a class method */
> ```

It starts from the big letter because it is a sentence? But it ends without '.' so it is not a sentence. I'm lost.
___
*[jenkins/lib/api.groovy, line 85 at r14](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MabZyOb4oeYf4pD-HS8:-MabZyOb4oeYf4pD-HS9:b-tb5ofb) ([raw file](https://github.com/pmem/dev-utils-kit/blob/b16cb29f92bcca5a1eaeb1e5691cbcf50106c227/jenkins/lib/api.groovy#L85)):*
> ```Groovy
> 	def script_output = readFile current_script_output_file
> 
> 	/* delete the log file */
> ```

Why this one is not a sentence?
___
*[jenkins/lib/api.groovy, line 89 at r14](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-Mab_2qbBMlVVnssecz5:-Mab_2qbBMlVVnssecz6:bnedmn3) ([raw file](https://github.com/pmem/dev-utils-kit/blob/b16cb29f92bcca5a1eaeb1e5691cbcf50106c227/jenkins/lib/api.groovy#L89)):*
> ```Groovy
> 
> 	/* capturing status is also disabling default behavior of `sh` - error when exit status != 0 */
> 	/* here restore that behavior if not requested otherwise */
> ```

Yet another, not a sentence. What is the rule?
___
*[jenkins/lib/api.groovy, line 326 at r14](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-Mab_qPgAirz4t3qEOnl:-Mab_qPh58UMZSW46fLt:bqvnqji) ([raw file](https://github.com/pmem/dev-utils-kit/blob/b16cb29f92bcca5a1eaeb1e5691cbcf50106c227/jenkins/lib/api.groovy#L326)):*
> ```Groovy
> }
> 
> /* this is necessary in order to closure work properly with enum after loading the file in the pipeline */
> ```

This is obviously a sentence. So please make it a sentence.
___
*[jenkins/lib/api.groovy, line 380 at r14](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MabaFBpASHr-uZ3Xtdl:-MabaFBpASHr-uZ3Xtdm:bu5unmp) ([raw file](https://github.com/pmem/dev-utils-kit/blob/b16cb29f92bcca5a1eaeb1e5691cbcf50106c227/jenkins/lib/api.groovy#L380)):*
> ```Groovy
> 	 *
> 	 * Groovy sandbox does not allow the creation of Date objects with constructor different than Unix milliseconds epoch,
> 	 * so we cannot count in days but only in milliseconds
> ```

Missing '.'
___
*[jenkins/lib/api.groovy, line 388 at r14](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MabaQDx6hK_D5g_Ah_N:-MabaQDy8uf71ipResD4:bv5r2h2) ([raw file](https://github.com/pmem/dev-utils-kit/blob/b16cb29f92bcca5a1eaeb1e5691cbcf50106c227/jenkins/lib/api.groovy#L388)):*
> ```Groovy
> 	def start_date = new Date(currentBuild.startTimeInMillis + one_day_in_ms)
> 
> 	/*  get week number and cast it to integer */
> ```

Please, make it a sentence.
___
*[jenkins/scripts/common.sh, line 26 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPtzN69R-vTEgpB2Y7:-Mabb1lX61uQzojpodp0:b8jrto9) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/common.sh#L26)):*
<details><summary><i>Previously, tszczyp (Tomasz Szczypiorowski) wrote…</i></summary><blockquote>

An entire output from these commands is visible in the logs, including situations where there are no dimms in the platform, so personally I don't find it really necessary to add additional warning, unless it's something you think will be useful here, then sure, I can add a warning of some sort.
</blockquote></details>

So, this script aims to print the output no matter if the configuration is valid or not. So `|| true` is just to prevent early exit. Any other consequences?
___
*[jenkins/scripts/common.sh, line 32 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPu9P0Bsj4sUgbT5Nr:-MabbXZS8b0lGyk9mmGn:b-9usvh8) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/common.sh#L32)):*
<details><summary><i>Previously, tszczyp (Tomasz Szczypiorowski) wrote…</i></summary><blockquote>

As mentioned, it is used to handle different systems. Since they're using a different package managers , we're doing this to ignore potential errors that may come along the way, that's all.
</blockquote></details>

The sad story is the errors are not potential, they are built-in. You will have errors each time and on all distributions I know of.

I understand it is a simplified implementation aimed simply to get the list of packages no matter what. The errors, in this case, do not have any further implications. Am I right?

If so, please leave a comment, since it is an obviously incorrect implementation but effective. I get it.
___
*[jenkins/scripts/common.sh, line 47 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPuGY19ty9YB-fnJe0:-MabcWbz4kyZCFLdJzg5:bakwslz) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/common.sh#L47)):*
<details><summary><i>Previously, tszczyp (Tomasz Szczypiorowski) wrote…</i></summary><blockquote>

I don't know how to answer that question, since I'm not an original author of this file, if it looks wrong I can separate them.
</blockquote></details>

Yes. Please separa [...]

2021-05-26 09:29 UTC, mramotowski commented
___
*[jenkins/lib/api.groovy, line 50 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZNfyzJ0zTeKozd9LpA:-Mac-1ZE-hibfYAreu22:bw50894) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/lib/api.groovy#L50)):*
<details><summary><i>Previously, nedved1 (Pawel Niedzwiecki) wrote…</i></summary><blockquote>

Jenkins api isn't that very useful in some cases. For example it's not possible to extract exit code and output string at the same time using only jenkins 'sh' command :p so Python script would not give anything. For the other hand Jenkins allows running groovy scripts within its instance.
</blockquote></details>

I do not agree with this answer.
Firstly is possible to extract exit code and output string at the same time using only jenkins 'sh' command from Jenkins job. Example:
Jenkins step:
`sh 'echo "this is my log"; this will give error'`
Jenkins output:
```
+ echo this is my log
this is my log
+ this will give error
/var/lib/jenkins/workspace/test22@tmp/durable-a55bfe65/script.sh: 1: this: not found
script returned exit code 127
```
Secondly if Python script would not give anything so how is groovy script giving anything?

Thirdly it is possible to call any scripts (e.g Python ) inside `sh` step. It is easier to maintain and to switch something as it is not dependebale on Jenkins. It can be used in other solutions or when you need to change your CI/CD tooling.

Lastly in my opinion a lot of things here is not needed. E.g `clone_repository(repo_url, branch, target_directory = '', keep_sha = true)` could be replaced in my opinion by one jenkins command:

`checkout([$class: 'GitSCM', branches: [[name: '*/stable-1.2']], extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: '/home/jenkins/test']], userRemoteConfigs: [[credentialsId: 'jenkins', url: 'https://github.com/pmem/pmdk']]])`

This command already have repo_url, branch, and target_directory. It also prints sha of cloned repository what can be seen in output below.  

Jenkins output:
```
The recommended git tool is: NONE
using credential jenkins
Cloning the remote Git repository
Cloning repository https://github.com/pmem/pmdk
 > git init /home/jenkins/test # timeout=10
Fetching upstream changes from https://github.com/pmem/pmdk
 > git --version # timeout=10
 > git --version # 'git version 2.25.1'
using GIT_ASKPASS to set credentials jenkins
 > git fetch --tags --force --progress -- https://github.com/pmem/pmdk +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url https://github.com/pmem/pmdk # timeout=10
 > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
Avoid second fetch
 > git rev-parse refs/remotes/origin/stable-1.2^{commit} # timeout=10
Checking out Revision 6c5b788833211348272066f18e49a18f7370d89a (refs/remotes/origin/stable-1.2)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 6c5b788833211348272066f18e49a18f7370d89a # timeout=10
Commit message: "common: 1.2.4 release"
First time build. Skipping changelog.
```


<!-- Sent from Reviewable.io -->

2021-05-27 09:21 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 3 files at r12, 6 of 6 files at r14.
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1)* status: all files reviewed, 38 unresolved discussions (waiting on @janekmi, @KFilipek, @lukaszstolarczuk, @mramotowski, @nedved1, and @tszczyp)

___
*[LICENSE, line 2 at r14](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MaYv6Uf7UcTHBWSGkqX:-Mah3-Ad86_9V5HRwwtv:b-4geiry) ([raw file](https://github.com/pmem/dev-utils-kit/blob/b16cb29f92bcca5a1eaeb1e5691cbcf50106c227/LICENSE#L2)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

If is it new repo I would prefer '2021' only
</blockquote></details>

it's a new LICENSE file, in a clean repo - \+1 for `2021` only
___
*[jenkins/scripts/common.sh, line 24 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPtoeq7BHMOj9aMr3u:-Mah5Y2r838xjctg3BPw:bb7p5eq) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/common.sh#L24)):*
<details><summary><i>Previously, tszczyp (Tomasz Szczypiorowski) wrote…</i></summary><blockquote>

Line updated, as well as a few more.
</blockquote></details>

thx!


<!-- Sent from Reviewable.io -->

2021-05-27 11:25 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1)* status: all files reviewed, 39 unresolved discussions (waiting on @janekmi, @KFilipek, @lukaszstolarczuk, @mramotowski, @nedved1, and @tszczyp)

*[a discussion](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MahYtVG0g7s1QLc9KfY:-MZPehMA1cjBl-8RNUpo:b-53dnj7) (no related file):*
BTW what is the point of making all of these public?
I remember we have agreed to do a single copy of all things common among our repositories but I do not remember why it makes sense for the Jenkins scripts.

---


<!-- Sent from Reviewable.io -->

2021-05-27 12:14 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1)* status: all files reviewed, 39 unresolved discussions (waiting on @janekmi, @KFilipek, @lukaszstolarczuk, @mramotowski, @nedved1, and @tszczyp)

*[a discussion](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MahYtVG0g7s1QLc9KfY:-MahjEY8AnJqwqE7JXhG:be2p0lm) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

BTW what is the point of making all of these public?
I remember we have agreed to do a single copy of all things common among our repositories but I do not remember why it makes sense for the Jenkins scripts.
</blockquote></details>

1. it's already public (within pmemkv repo)... so why not? What would be the case to hide it now...?
2. it's a cool solution to use (possibly) everywhere you want - if e.g. an external contributor or a client would like to set up their own builds, it's possible with this.

---
___
*[jenkins/lib/api.groovy, line 50 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZNfyzJ0zTeKozd9LpA:-MahiAGyEqP97irNAUfw:b-8mizec) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/lib/api.groovy#L50)):*
<details><summary><i>Previously, mramotowski wrote…</i></summary><blockquote>

I do not agree with this answer.
Firstly is possible to extract exit code and output string at the same time using only jenkins 'sh' command from Jenkins job. Example:
Jenkins step:
`sh 'echo "this is my log"; this will give error'`
Jenkins output:
```
+ echo this is my log
this is my log
+ this will give error
/var/lib/jenkins/workspace/test22@tmp/durable-a55bfe65/script.sh: 1: this: not found
script returned exit code 127
```
Secondly if Python script would not give anything so how is groovy script giving anything?

Thirdly it is possible to call any scripts (e.g Python ) inside `sh` step. It is easier to maintain and to switch something as it is not dependebale on Jenkins. It can be used in other solutions or when you need to change your CI/CD tooling.

Lastly in my opinion a lot of things here is not needed. E.g `clone_repository(repo_url, branch, target_directory = '', keep_sha = true)` could be replaced in my opinion by one jenkins command:

`checkout([$class: 'GitSCM', branches: [[name: '*/stable-1.2']], extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: '/home/jenkins/test']], userRemoteConfigs: [[credentialsId: 'jenkins', url: 'https://github.com/pmem/pmdk']]])`

This command already have repo_url, branch, and target_directory. It also prints sha of cloned repository what can be seen in output below.  

Jenkins output:
```
The recommended git tool is: NONE
using credential jenkins
Cloning the remote Git repository
Cloning repository https://github.com/pmem/pmdk
 > git init /home/jenkins/test # timeout=10
Fetching upstream changes from https://github.com/pmem/pmdk
 > git --version # timeout=10
 > git --version # 'git version 2.25.1'
using GIT_ASKPASS to set credentials jenkins
 > git fetch --tags --force --progress -- https://github.com/pmem/pmdk +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url https://github.com/pmem/pmdk # timeout=10
 > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
Avoid second fetch
 > git rev-parse refs/remotes/origin/stable-1.2^{commit} # timeout=10
Checking out Revision 6c5b788833211348272066f18e49a18f7370d89a (refs/remotes/origin/stable-1.2)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 6c5b788833211348272066f18e49a18f7370d89a # timeout=10
Commit message: "common: 1.2.4 release"
First time build. Skipping changelog.
```

</blockquote></details>

I'd say, perhaps not to linger even more with this PR, pls file an issue within this repository to mark some possible improvements.

We could make the process of upgrading and polishing this code last forever, but... our main goal is to make this usable (I believe it is already) and start using this with our instances... Right now we have to wait with libpmemobj-cpp jenkins builds, because of this PR (and we have to manually execute Jenkins from our branch, which is far from ideal ;-) ).


<!-- Sent from Reviewable.io -->

2021-05-27 13:06 UTC, draghan reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1)* status: all files reviewed, 39 unresolved discussions (waiting on @janekmi, @KFilipek, @lukaszstolarczuk, @mramotowski, @nedved1, and @tszczyp)

___
*[jenkins/lib/api.groovy, line 50 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZNfyzJ0zTeKozd9LpA:-Mahtj6s7oTmCad4WTPK:bxoplwk) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/lib/api.groovy#L50)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I'd say, perhaps not to linger even more with this PR, pls file an issue within this repository to mark some possible improvements.

We could make the process of upgrading and polishing this code last forever, but... our main goal is to make this usable (I believe it is already) and start using this with our instances... Right now we have to wait with libpmemobj-cpp jenkins builds, because of this PR (and we have to manually execute Jenkins from our branch, which is far from ideal ;-) ).
</blockquote></details>

This is the solution implemented to suit needs of PMDK CW Val Jenkins, so not every aspect of it may be visible to you at a glance.

We were extending Jenkins' API, because it simply lacked basic functionalities we needed.
As @nedved1  pointed out, the prime example: you can't capture both stdout and return code from a script call ([related issue](https://issues.jenkins.io/browse/JENKINS-44930?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aall-tabpanel)). Yes, @mramotowski , Jenkins will print out stdout and retcode, but you can't do anything with that from the pipeline's level. You can either capture and process output from a call and ignore retcode (and possible failures will immediately break the stage's execution), or process retcode but then you can't process stdout.

You can't workaround basic Jenkins' limitations with external scripts, which has to be called by the handicapped Jenkins' functionalities. :) You have to do it from Jenkins' internals - by fixing its sources as it's FOSS (good luck with that, they are discussing a need for capturing both stdout and retcode since 2017) or by writing extensions. Even if you somehow could overcome Jenkins' limitations via external scripts, they won't be portable to different CI tool, because they will be designed to fix particular Jenkins' flaws.

Other things were added for simplicity of the pipelines, e.g. the mentioned facade for repo clonning. We had multiple pipelines, in each we had to clone multiple repos, where some of them were from Github, some from Gitlab, each required different set of parameters - enclosing this `checkout` step inside a simple `clone_repo` function significantly reduced boilerplate code and kept the code DRY.


<!-- Sent from Reviewable.io -->

2021-05-31 08:00 UTC, mramotowski commented
___
*[jenkins/lib/api.groovy, line 50 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZNfyzJ0zTeKozd9LpA:-Mb0PnMkCmsQ7-aPyzVt:b29zm0w) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/lib/api.groovy#L50)):*
<details><summary><i>Previously, draghan (Dariusz Pyś) wrote…</i></summary><blockquote>

This is the solution implemented to suit needs of PMDK CW Val Jenkins, so not every aspect of it may be visible to you at a glance.

We were extending Jenkins' API, because it simply lacked basic functionalities we needed.
As @nedved1  pointed out, the prime example: you can't capture both stdout and return code from a script call ([related issue](https://issues.jenkins.io/browse/JENKINS-44930?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aall-tabpanel)). Yes, @mramotowski , Jenkins will print out stdout and retcode, but you can't do anything with that from the pipeline's level. You can either capture and process output from a call and ignore retcode (and possible failures will immediately break the stage's execution), or process retcode but then you can't process stdout.

You can't workaround basic Jenkins' limitations with external scripts, which has to be called by the handicapped Jenkins' functionalities. :) You have to do it from Jenkins' internals - by fixing its sources as it's FOSS (good luck with that, they are discussing a need for capturing both stdout and retcode since 2017) or by writing extensions. Even if you somehow could overcome Jenkins' limitations via external scripts, they won't be portable to different CI tool, because they will be designed to fix particular Jenkins' flaws.

Other things were added for simplicity of the pipelines, e.g. the mentioned facade for repo clonning. We had multiple pipelines, in each we had to clone multiple repos, where some of them were from Github, some from Gitlab, each required different set of parameters - enclosing this `checkout` step inside a simple `clone_repo` function significantly reduced boilerplate code and kept the code DRY.
</blockquote></details>

Dunno about this whole PMDK CW Val Jenkins, but if it is specific to some group/repo it should be highlighted in README. Cause for now it seems it is extension for Jenkins pipelines overall.

I looked into that issue and from example of JD Friedrikson, I can see it is possible. Although I understand that it can be a pain to build such solution each time you need it and you wanted to have as function. I also agree with Jesse Glick: `The Pipeline script is glue code for automating Jenkins operations. Your build processes are your own. `. Still I dunno, why you need it and why you can't workaround basic Jenkins' limitations with external scripts? Could you provide me an example, so I can understand it better? What problem it solves?

I don't agree with your vision of pipelines simplification. I think it is not good way to re-write Jenkins basic commands like sh, echo, checkout. For close group of people it can be simplification but lets think wider. If there will be situation when new people will come that already knows Jenkins or there will be external contributor that will like to do the change in Jenkinsfile it will be hard, cause the code of pipeline is not standard. What I mean by standard is Jenkins pipeline [syntax](https://www.jenkins.io/doc/book/pipeline/syntax/) and [step](https://www.jenkins.io/doc/pipeline/steps/) reference.


<!-- Sent from Reviewable.io -->

2021-06-07 12:08 UTC, tszczyp reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1)* status: 1 of 7 files reviewed, 39 unresolved discussions (waiting on @janekmi, @KFilipek, @lukaszstolarczuk, @mramotowski, and @tszczyp)

___
*[LICENSE, line 2 at r14](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MaYv6Uf7UcTHBWSGkqX:-Mb_ukeZ7971AJ1VtSrI:b-896fix) ([raw file](https://github.com/pmem/dev-utils-kit/blob/b16cb29f92bcca5a1eaeb1e5691cbcf50106c227/LICENSE#L2)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

it's a new LICENSE file, in a clean repo - \+1 for `2021` only
</blockquote></details>

Done.
___
*[jenkins/README.md, line 9 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPh_Y-4x_VwoRx7K5x:-Mb_un7tD2ehtB00NKnr:b-hxtqv3) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/README.md#L9)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think it is a good idea.
</blockquote></details>

Added a note below with information about acquiring Jenkins
___
*[jenkins/lib/api.groovy, line 32 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPv6740sWwnDewPxJM:-Mb_vDpK-KdoOOYob6EV:boczm4j) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/lib/api.groovy#L32)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You are making an absolute path from a relative one. I do not know what interpolation means in this context.
</blockquote></details>

Ok then, I changed the comment which describe this function.
___
*[jenkins/lib/api.groovy, line 42 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPvYot9JUdipEfnOi0:-Mb_vhN-8LOVNjbT3zcf:b-xf9qqf) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/lib/api.groovy#L42)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

The form is not used consistently. You use both forms. The third-person singular (e.g. runs) and the basic (e.g. return, add).
</blockquote></details>

Would you kindly show me some examples, I'm lost here.
___
*[jenkins/lib/api.groovy, line 50 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZNfyzJ0zTeKozd9LpA:-Mb_wC7X9K_eJizfCApV:b-pz33wo) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/lib/api.groovy#L50)):*
<details><summary><i>Previously, mramotowski wrote…</i></summary><blockquote>

Dunno about this whole PMDK CW Val Jenkins, but if it is specific to some group/repo it should be highlighted in README. Cause for now it seems it is extension for Jenkins pipelines overall.

I looked into that issue and from example of JD Friedrikson, I can see it is possible. Although I understand that it can be a pain to build such solution each time you need it and you wanted to have as function. I also agree with Jesse Glick: `The Pipeline script is glue code for automating Jenkins operations. Your build processes are your own. `. Still I dunno, why you need it and why you can't workaround basic Jenkins' limitations with external scripts? Could you provide me an example, so I can understand it better? What problem it solves?

I don't agree with your vision of pipelines simplification. I think it is not good way to re-write Jenkins basic commands like sh, echo, checkout. For close group of people it can be simplification but lets think wider. If there will be situation when new people will come that already knows Jenkins or there will be external contributor that will like to do the change in Jenkinsfile it will be hard, cause the code of pipeline is not standard. What I mean by standard is Jenkins pipeline [syntax](https://www.jenkins.io/doc/book/pipeline/syntax/) and [step](https://www.jenkins.io/doc/pipeline/steps/) reference.
</blockquote></details>

Just a random comment passing by.
___
*[jenkins/lib/api.groovy, line 28 at r14](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MabYJp7A36CJ28m7MR8:-Mb_vCmOEGki4i7FrReo:b-896fix) ([raw file](https://github.com/pmem/dev-utils-kit/blob/b16cb29f92bcca5a1eaeb1e5691cbcf50106c227/jenkins/lib/api.groovy#L28)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Missing '.' at the end.
</blockquote></details>

Done.
___
*[jenkins/lib/api.groovy, line 38 at r14](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MabYkZD1sj4D_20ZtAM:-Mb_vSQvDTkDkyxFyIDp:b-q3u5fx) ([raw file](https://github.com/pmem/dev-utils-kit/blob/b16cb29f92bcca5a1eaeb1e5691cbcf50106c227/jenkins/lib/api.groovy#L38)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It starts from the big letter because it is a sentence? But it ends without '.' so it is not a sentence. I'm lost.
</blockquote></details>

'.' added.
___
*[jenkins/lib/api.groovy, line 85 at r14](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MabZyOb4oeYf4pD-HS8:-Mb_wN3g5taAvdhioUmv:b-896fix) ([raw file](https://github.com/pmem/dev-utils-kit/blob/b16cb29f92bcca5a1eaeb1e5691cbcf50106c227/jenkins/lib/api.groovy#L85)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Why this one is not a sentence?
</blockquote></details>

Done.
___
*[jenkins/lib/api.groovy, line 89 at r14](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-Mab_2qbBMlVVnssecz5:-Mb_wNlB6o5SgBljWIKE:b-896fix) ([raw file](https://github.com/pmem/dev-utils-kit/blob/b16cb29f92bcca5a1eaeb1e5691cbcf50106c227/jenkins/lib/api.groovy#L89)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Yet another, not a sentence. What is the rule?
</blockquote></details>

Done.
___
*[jenkins/lib/api.groovy, line 326 at r14](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-Mab_qPgAirz4t3qEOnl:-Mb_x8CKBTXcrDYm5a_h:b-896fix) ([raw file](https://github.com/pmem/dev-utils-kit/blob/b16cb29f92bcca5a1eaeb1e5691cbcf50106c227/jenkins/lib/api.groovy#L326)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This is obviously a sentence. So please make it a sentence.
</blockquote></details>

Done.
___
*[jenkins/lib/api.groovy, line 380 at r14](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MabaFBpASHr-uZ3Xtdl:-Mb_xD2g13DgJZNLBkQv:b-896fix) ([raw file](https://github.com/pmem/dev-utils-kit/blob/b16cb29f92bcca5a1eaeb1e5691cbcf50106c227/jenkins/lib/api.groovy#L380)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Missing '.'
</blockquote></details>

Done.
___
*[jenkins/lib/api.groovy, line 388 at r14](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MabaQDx6hK_D5g_Ah_N:-Mb_xDw0C5CcCoHVRFNN:b-896fix) ([raw file](https://github.com/pmem/dev-utils-kit/blob/b16cb29f92bcca5a1eaeb1e5691cbcf50106c227/jenkins/lib/api.groovy#L388)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please, make it a sentence.
</blockquote></details>

Done.
___
*[jenkins/scripts/common.sh, line 26 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPtzN69R-vTEgpB2Y7:-Mb_xOdX0Hcg8r73uDEs:bi8ffet) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/common.sh#L26)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

So, this script aims to print the output no matter if the configuration is valid or not. So `|| true` is just to prevent early exit. Any other consequences?
</blockquote></details>

Not that I'm aware of, it's prevention of an early exit as you mentioned.
___
*[jenkins/scripts/common.sh, line 32 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPu9P0Bsj4sUgbT5Nr:-Mb_xqkxExr1SHo2hs8U:bj0wwnz) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446 [...]

2021-06-07 12:30 UTC, tszczyp reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1)* status: 1 of 7 files reviewed, 39 unresolved discussions (waiting on @janekmi, @KFilipek, @lukaszstolarczuk, @mramotowski, and @tszczyp)

___
*[jenkins/scripts/createNamespace.sh, line 9 at r14](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MabebVs5siJNCWuA1_Y:-MbaQHUcE1Av2gsIleo-:b28khwe) ([raw file](https://github.com/pmem/dev-utils-kit/blob/b16cb29f92bcca5a1eaeb1e5691cbcf50106c227/jenkins/scripts/createNamespace.sh#L9)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

> The region's type(?) which means dax namespaces, as seen by the command 'ipmctl show -region'.

Please correct 'type' if ipmctl uses a different name for it.
</blockquote></details>

I have to partially disagree, I added comments with more information about the regions, but I cannot change it to the way you see it, as regions doesn't have a type by itself, only namespaces. Right now, the process restricts the user to create one namespace of  a given type to one region only, as it's used by pmem tests.
___
*[jenkins/scripts/createNamespace.sh, line 11 at r14](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MabfV_S6zCjrZ7O_hWL:-MbaRi8H3fbGt-G-Pe2a:bribihm) ([raw file](https://github.com/pmem/dev-utils-kit/blob/b16cb29f92bcca5a1eaeb1e5691cbcf50106c227/jenkins/scripts/createNamespace.sh#L11)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please rephrase it as above.
</blockquote></details>

As above.
___
*[jenkins/scripts/removeNamespaces.sh, line 11 at r14](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-Mabi_kf32c15MtmD8n7:-MbaRoWbBCJ0WKWBOgJY:b-4frjqg) ([raw file](https://github.com/pmem/dev-utils-kit/blob/b16cb29f92bcca5a1eaeb1e5691cbcf50106c227/jenkins/scripts/removeNamespaces.sh#L11)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

MOUNT_POINT or MOUNTPOINT?
</blockquote></details>

One chosen, updated.


<!-- Sent from Reviewable.io -->

2021-06-10 15:07 UTC, lukaszstolarczuk reviewed
> Reviewed 6 of 6 files at r15.
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1)* status: all files reviewed, 42 unresolved discussions (waiting on @janekmi, @KFilipek, @mramotowski, and @tszczyp)

___
*[jenkins/lib/api.groovy, line 42 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPvYot9JUdipEfnOi0:-MbqORrx5X1kj0V_9k0X:b2yw12u) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/lib/api.groovy#L42)):*
<details><summary><i>Previously, tszczyp (Tomasz Szczypiorowski) wrote…</i></summary><blockquote>

Would you kindly show me some examples, I'm lost here.
</blockquote></details>

you use an inconsistent form of verbs, sometimes it's `Run` and sometimes it's `Runs`, e.g.

`**Prints* provided text to the output log.` for `run_echo` method
and
`**Add** repository revision to saved revisions.` in `save_git_revision` method

what Janek is saying, is that you should pick one form and stick to it in all comments (at least the ones describing functions)
___
*[jenkins/scripts/common.sh, line 32 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPu9P0Bsj4sUgbT5Nr:-MbqPONz8c_Ub1nAz-jO:by4pn67) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/common.sh#L32)):*
<details><summary><i>Previously, tszczyp (Tomasz Szczypiorowski) wrote…</i></summary><blockquote>

`I understand it is a simplified implementation aimed simply to get the list of packages no matter what. The errors, in this case, do not have any further implications. Am I right?`
Yes, you're right.
</blockquote></details>

... sooo, as Janek asked, please put some comment in the code
___
*[jenkins/scripts/common.sh, line 47 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPuGY19ty9YB-fnJe0:-MbqPYdREykr2mk2Ujp_:b492o6h) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/common.sh#L47)):*
<details><summary><i>Previously, tszczyp (Tomasz Szczypiorowski) wrote…</i></summary><blockquote>

Separated.
</blockquote></details>

I guess it was in one line since it was a second command related to the same package manager - see there is 1 command for `zypper`, 1 for `dnf` and 2 for `apt`. I guess it's ok like it is right now.
___
*[jenkins/scripts/createNamespace.sh, line 16 at r14](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MabfgBv9DkmmXhR8uaU:-MbqQJoP-xt431VQWl7d:bodqegd) ([raw file](https://github.com/pmem/dev-utils-kit/blob/b16cb29f92bcca5a1eaeb1e5691cbcf50106c227/jenkins/scripts/createNamespace.sh#L16)):*
<details><summary><i>Previously, tszczyp (Tomasz Szczypiorowski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

you've deleted now the space between `#` and `The`
___
*[jenkins/scripts/createNamespace.sh, line 110 at r15](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MbqRlZO4_kNzlQpJGhW:-MbqRlZO4_kNzlQpJGhX:bmh19k5) ([raw file](https://github.com/pmem/dev-utils-kit/blob/732e4a970f1a82c0bcea95b4026fe4574ccb3e3e/jenkins/scripts/createNamespace.sh#L110)):*
> ```Shell
> if $CREATE_PMEM; then
> 
> 	if [ ! -d "$MOUNT_POINT" ]; then
> ```

is it `MOUNT_POINT` or `MOUNTPOINT` (as above)?
___
*[jenkins/scripts/createNamespace.sh, line 129 at r15](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MbqRKsSB2btDgRMTzOo:-MbqRKsSB2btDgRMTzOp:b-76566q) ([raw file](https://github.com/pmem/dev-utils-kit/blob/732e4a970f1a82c0bcea95b4026fe4574ccb3e3e/jenkins/scripts/createNamespace.sh#L129)):*
> ```Shell
> # /sys/bus/nd/devices/ndbus*/region*/dax*/resource
> # /sys/bus/nd/devices/ndbus*/region*/pfn*/resource
> # /sys/bus/nd/devices/ndbus*/region*/namespace*/resource
> ```

the last two are not chmod'ed below - is that expected?
___
*[jenkins/scripts/removeNamespaces.sh, line 9 at r15](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MbqSA3B0cKJ0N6sSG40:-MbqSA3B0cKJ0N6sSG41:b-jj975f) ([raw file](https://github.com/pmem/dev-utils-kit/blob/732e4a970f1a82c0bcea95b4026fe4574ccb3e3e/jenkins/scripts/removeNamespaces.sh#L9)):*
> ```Shell
> 
> echo "Clearing all existing namespaces"
> MOUNTPOINT=$(lsblk | grep "pmem" | tr -s ' ' | cut -d ' ' -f 7)
> ```

it should be plural - MOUNTPOINTS


<!-- Sent from Reviewable.io -->

2021-06-10 15:10 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1)* status: all files reviewed, 42 unresolved discussions (waiting on @janekmi, @KFilipek, @mramotowski, and @tszczyp)

___
*[jenkins/scripts/removeNamespaces.sh, line 11 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPnWNs1jBMYpLPUUAU:-MbqT4xF8_tc7Wowc45K:b4u3pb5) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/removeNamespaces.sh#L11)):*
<details><summary><i>Previously, tszczyp (Tomasz Szczypiorowski) wrote…</i></summary><blockquote>

Functionality was changed, now it should work regardless as long as mountpoint is 'pmem' in any way. 
</blockquote></details>

you grep the whole output of `lsblk`, so if there's a device called e.g. `/dev/pmem0` and it's not mounted the `m` will be an empty string - so the `umount` will fail... right?


<!-- Sent from Reviewable.io -->

2021-06-15 10:39 UTC, lukaszstolarczuk commented
@tszczyp, ping - any update here?

// I'd really, really love to finish up with this PR 😃

2021-06-15 10:48 UTC, tszczyp reviewed
More updates will come soon :)

> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-:-McEHHMEE1YQe2h9333_:b-2zgxcm)* status: all files reviewed, 42 unresolved discussions (waiting on @janekmi, @KFilipek, @mramotowski, and @tszczyp)



<!-- Sent from Reviewable.io -->

2021-06-18 13:20 UTC, tszczyp reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1)* status: 3 of 7 files reviewed, 42 unresolved discussions (waiting on @janekmi, @KFilipek, @lukaszstolarczuk, @mramotowski, and @tszczyp)

___
*[jenkins/lib/api.groovy, line 42 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPvYot9JUdipEfnOi0:-McUDkt8BG7DvK35z-sR:byox2or) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/lib/api.groovy#L42)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you use an inconsistent form of verbs, sometimes it's `Run` and sometimes it's `Runs`, e.g.

`**Prints* provided text to the output log.` for `run_echo` method
and
`**Add** repository revision to saved revisions.` in `save_git_revision` method

what Janek is saying, is that you should pick one form and stick to it in all comments (at least the ones describing functions)
</blockquote></details>

Ok then, I changed some verbs throughout the file, function descriptions should have consistent forms, although I didn't change any comments for parameters as well as random lines outside of functions.
___
*[jenkins/scripts/common.sh, line 32 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPu9P0Bsj4sUgbT5Nr:-McUEMsfB3QvDVn0ojWj:bn2fa4o) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/common.sh#L32)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

... sooo, as Janek asked, please put some comment in the code
</blockquote></details>

...and I added some :D let me know if they're satisfactory.
___
*[jenkins/scripts/common.sh, line 47 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPuGY19ty9YB-fnJe0:-McUGg_V47i0XjChwkU7:bppqmts) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/common.sh#L47)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I guess it was in one line since it was a second command related to the same package manager - see there is 1 command for `zypper`, 1 for `dnf` and 2 for `apt`. I guess it's ok like it is right now.
</blockquote></details>

Good, I assume this comment can be resolved now :)
___
*[jenkins/scripts/common.sh, line 73 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPuQTl4PeMzlnonxLR:-McUEiKM22O7Dj_jXMla:buzonbo) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/common.sh#L73)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It is too easy to silent errors coming from potential bad code with this technique. So providing a good explanation allows to:

1. Forcing thinking why you are doing what you are doing. Because it is a lot easier to do this than well explain why.
2. Easily checking if silencing in each particular case is (still) necessary.
</blockquote></details>

Well I kind of cheated here to get rid of this || true
___
*[jenkins/scripts/createNamespace.sh, line 16 at r14](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MabfgBv9DkmmXhR8uaU:-McUErl51E8IjSwGnfJd:bnjty6m) ([raw file](https://github.com/pmem/dev-utils-kit/blob/b16cb29f92bcca5a1eaeb1e5691cbcf50106c227/jenkins/scripts/createNamespace.sh#L16)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you've deleted now the space between `#` and `The`
</blockquote></details>

Yup, thanks for noticing.
___
*[jenkins/scripts/createNamespace.sh, line 110 at r15](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MbqRlZO4_kNzlQpJGhW:-McUEvn00KWIQgYjwisB:b94jzob) ([raw file](https://github.com/pmem/dev-utils-kit/blob/732e4a970f1a82c0bcea95b4026fe4574ccb3e3e/jenkins/scripts/createNamespace.sh#L110)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

is it `MOUNT_POINT` or `MOUNTPOINT` (as above)?
</blockquote></details>

Updated, thanks.
___
*[jenkins/scripts/createNamespace.sh, line 129 at r15](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MbqRKsSB2btDgRMTzOo:-McUF006-XaBWSLB_XjF:b-uao1ga) ([raw file](https://github.com/pmem/dev-utils-kit/blob/732e4a970f1a82c0bcea95b4026fe4574ccb3e3e/jenkins/scripts/createNamespace.sh#L129)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

the last two are not chmod'ed below - is that expected?
</blockquote></details>

So far this worked, so I guess it's expected, unless you want me to add them.
___
*[jenkins/scripts/removeNamespaces.sh, line 11 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPnWNs1jBMYpLPUUAU:-McUFIvI5ndoyjvURsS3:b25wysq) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/removeNamespaces.sh#L11)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you grep the whole output of `lsblk`, so if there's a device called e.g. `/dev/pmem0` and it's not mounted the `m` will be an empty string - so the `umount` will fail... right?
</blockquote></details>

Right, it's updated again, this time no matter how device is called or what its mountpoint path will be, it will work, if the device is not mounted at all it will simply skip this with no errors.
___
*[jenkins/scripts/removeNamespaces.sh, line 19 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPnqLvE4N92gXl_bWX:-McUFztx62v3CKHLPPPE:bfli35z) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/removeNamespaces.sh#L19)):*
<details><summary><i>Previously, tszczyp (Tomasz Szczypiorowski) wrote…</i></summary><blockquote>

Just like in other cases, we are allowing singular commands to fail, to prevent a failure of an entire execution.
</blockquote></details>

Update - it's not needed anymore.
___
*[jenkins/scripts/removeNamespaces.sh, line 9 at r15](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MbqSA3B0cKJ0N6sSG40:-McUFCpI87rgwcUXRylc:b-60car2) ([raw file](https://github.com/pmem/dev-utils-kit/blob/732e4a970f1a82c0bcea95b4026fe4574ccb3e3e/jenkins/scripts/removeNamespaces.sh#L9)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

it should be plural - MOUNTPOINTS
</blockquote></details>

Ok then.


<!-- Sent from Reviewable.io -->

2021-06-18 13:44 UTC, lukaszstolarczuk reviewed
looks good to me ;)

@janekmi, pls let us know what you think, I'd really appreciate this PR to work for our Jenkins (finally :wink: )

> Reviewed 4 of 4 files at r16.
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-:-McUM6Sh5G6hk3z-MDPs:btfb731)* status: all files reviewed, 39 unresolved discussions (waiting on @janekmi, @KFilipek, @mramotowski, and @tszczyp)

___
*[jenkins/scripts/common.sh, line 32 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPu9P0Bsj4sUgbT5Nr:-McULGKMBCInxtdyjfno:b-k6qxkg) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/common.sh#L32)):*
<details><summary><i>Previously, tszczyp (Tomasz Szczypiorowski) wrote…</i></summary><blockquote>

...and I added some :D let me know if they're satisfactory.
</blockquote></details>

thx :)
___
*[jenkins/scripts/createNamespace.sh, line 129 at r15](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MbqRKsSB2btDgRMTzOo:-McULWNU9vXsvfWZWQEV:b-4ymd1n) ([raw file](https://github.com/pmem/dev-utils-kit/blob/732e4a970f1a82c0bcea95b4026fe4574ccb3e3e/jenkins/scripts/createNamespace.sh#L129)):*
<details><summary><i>Previously, tszczyp (Tomasz Szczypiorowski) wrote…</i></summary><blockquote>

So far this worked, so I guess it's expected, unless you want me to add them.
</blockquote></details>

nope, thx, I was just double-checking ;)
___
*[jenkins/scripts/removeNamespaces.sh, line 11 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPnWNs1jBMYpLPUUAU:-McULmAd5Wpc0gJi1vaa:b-q74txj) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/scripts/removeNamespaces.sh#L11)):*
<details><summary><i>Previously, tszczyp (Tomasz Szczypiorowski) wrote…</i></summary><blockquote>

Right, it's updated again, this time no matter how device is called or what its mountpoint path will be, it will work, if the device is not mounted at all it will simply skip this with no errors.
</blockquote></details>

great!


<!-- Sent from Reviewable.io -->

2021-06-23 12:20 UTC, KFilipek reviewed
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> 

> Reviewed 1 of 6 files at r15.
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-:-Mcsnv3l932ZhgMxFb0-:b-uwkowd)* status: all files reviewed, 38 unresolved discussions (waiting on @janekmi, @mramotowski, and @tszczyp)



<!-- Sent from Reviewable.io -->

2021-06-23 12:39 UTC, nedved1 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1)* status: all files reviewed, 38 unresolved discussions (waiting on @janekmi and @mramotowski)

___
*[jenkins/lib/api.groovy, line 142 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPygcM2zSVDiM05wwG:-McspzyFEfZ9Jy-zAVwt:b-dm463) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/lib/api.groovy#L142)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

The interface you have here does not a native echo function? You have to build one on your own?
</blockquote></details>

Bash echo is used for markings in the standard output (Logs from build, tests, system_info, etc. are stored additionally on tested server - for later use and to be archived). 


<!-- Sent from Reviewable.io -->

2021-07-09 09:36 UTC, tszczyp reviewed
I see that there are still a few comments left that needs to be resolved, unless answers provided in them by me or nedved1 are unsatisfactory, then let me know. If there are no more comments beside this I believe it's time to end this? :D

> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-:-Me9aAp78McjnPfJtBsh:bp085ax)* status: all files reviewed, 38 unresolved discussions (waiting on @janekmi and @mramotowski)



<!-- Sent from Reviewable.io -->

2021-07-09 09:42 UTC, mramotowski reviewed
> Just a random comment passing by.
is not a satisfactory answer :)

> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-:-Me9cx651ewJHikOGqxb:bbmw08p)* status: all files reviewed, 38 unresolved discussions (waiting on @janekmi and @mramotowski)



<!-- Sent from Reviewable.io -->

2021-07-12 10:30 UTC, tszczyp reviewed
Sure, I agree, but this particular discussion wasn't exactly going anywhere, and I don't think that bigger changes than what already was done during this review should be considered at this point, as they sounds like new features/reworks. Personally I'd like to end this if possible. 

> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-:-MePD6FI2gCbL1UZqvuW:b1n4fpe)* status: all files reviewed, 38 unresolved discussions (waiting on @janekmi and @mramotowski)



<!-- Sent from Reviewable.io -->

2021-07-13 09:05 UTC, KFilipek reviewed
@janekmi could you resolve pending threads?

> Reviewed 1 of 6 files at r15, 1 of 4 files at r16.
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-:-MeU6-NL9LAdrpS61CFc:b7wkkqd)* status: all files reviewed, 38 unresolved discussions (waiting on @janekmi and @mramotowski)



<!-- Sent from Reviewable.io -->

2021-07-13 09:20 UTC, mramotowski reviewed
@tszczyp I understand but are there any plans to change it, fix it, answer it or create an issue for it? Or just silently merge and not do anything? Cause for me as reviewer question is still not answered. I still don't know what issue such solution is fixing and why jenkins api + scripts is not enough. I asked for example and there is none. I think month is really long time reply. I don't expect it to be changed here and now. However, I am aware that if it gets merged now without any further decision, it will probably never be changed. But as I wrote it just question final decision goes to @janekmi .

> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-:-MeU6uUp4WaXaw4WNoyK:b-ed4i0g)* status: all files reviewed, 38 unresolved discussions (waiting on @janekmi and @mramotowski)



<!-- Sent from Reviewable.io -->

2021-07-21 10:47 UTC, lukaszstolarczuk reviewed
@tszczyp I think I agree with @mramotowski - we should either fix it here or create an issue for it. Please update us on his concern.

> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-:-Mf7f5nWBQZtxj56zRI3:bk1nkmd)* status: all files reviewed, 38 unresolved discussions (waiting on @janekmi and @mramotowski)



<!-- Sent from Reviewable.io -->

2021-07-29 10:08 UTC, janekmi requested changes
> Reviewed 2 of 6 files at r15, 3 of 4 files at r16.
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1)* status: all files reviewed, 12 unresolved discussions (waiting on @mramotowski, @nedved1, and @tszczyp)

___
*[jenkins/README.md, line 14 at r16](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MflMi8H4G5Byijltzrh:-MflMi8H4G5Byijltzri:bkgxyat) ([raw file](https://github.com/pmem/dev-utils-kit/blob/eca4cc87a120ea0cb3a2322e3a17fea34a53bad7/jenkins/README.md#L14)):*
> ```Markdown
> 
> ## Quick access to Jenkins
> To gain access to a working Jenkins instance quickly, use links provided below and follow instructions contained therein:
> ```

the links
___
*[jenkins/README.md, line 91 at r16](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MflaxAE5vxpmc8KAHe_:-MflaxAE5vxpmc8KAHea:b-90tnn6) ([raw file](https://github.com/pmem/dev-utils-kit/blob/eca4cc87a120ea0cb3a2322e3a17fea34a53bad7/jenkins/README.md#L91)):*
> ```Markdown
> 
> ### In-process Script Approval
> By default, Jenkins will prevent running new groovy scripts which will cause our job to fail. After each fail caused by an unapproved script, it is needed to accept this script. Unfortunately, this will be necessary to repeat several times, by launching this job repeatedly (only after creating this job, for the first time).
> ```

only after creating this job, for the first tim -> when running the job for the first time
___
*[jenkins/lib/api.groovy, line 50 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZNfyzJ0zTeKozd9LpA:-Mflc7JUEUf4btXL9ug6:b8ftgh2) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/lib/api.groovy#L50)):*
<details><summary><i>Previously, tszczyp (Tomasz Szczypiorowski) wrote…</i></summary><blockquote>

Just a random comment passing by.
</blockquote></details>

I'm accepting this only to merge this PR at last.
___
*[jenkins/lib/api.groovy, line 142 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPygcM2zSVDiM05wwG:-Mflcq_RCTV0Dk7lJB_F:b-vu88r3) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/lib/api.groovy#L142)):*
<details><summary><i>Previously, nedved1 (Pawel Niedzwiecki) wrote…</i></summary><blockquote>

Bash echo is used for markings in the standard output (Logs from build, tests, system_info, etc. are stored additionally on tested server - for later use and to be archived). 
</blockquote></details>

So please describe what this function is good for in the comment.
___
*[jenkins/lib/api.groovy, line 360 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZQ20Sg-XIVDuWPBu6v:-MfldAl1BLjXx5seDY0p:b51vy1p) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/lib/api.groovy#L360)):*
<details><summary><i>Previously, nedved1 (Pawel Niedzwiecki) wrote…</i></summary><blockquote>

Default on the jenkins instance.
</blockquote></details>

Srsly Jenkins ignores the system configuration on this matter? You are absolutely sure?
___
*[jenkins/lib/api.groovy, line 28 at r16](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-Mflb712DlHc_l47qUuq:-Mflb712DlHc_l47qUur:b-7etkoe) ([raw file](https://github.com/pmem/dev-utils-kit/blob/eca4cc87a120ea0cb3a2322e3a17fea34a53bad7/jenkins/lib/api.groovy#L28)):*
> ```Groovy
> REVISION_FILENAME = "sha.txt"
> 
> /* A list of git revisions used in a job. It should contain list of dicts (with 'url' and 'sha' keys). */
> ```

a list of dicts
___
*[jenkins/lib/api.groovy, line 388 at r16](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MfldWvC2ezv2dWMMXnP:-MfldWvC2ezv2dWMMXnQ:b-7sdmtt) ([raw file](https://github.com/pmem/dev-utils-kit/blob/eca4cc87a120ea0cb3a2322e3a17fea34a53bad7/jenkins/lib/api.groovy#L388)):*
> ```Groovy
> 	def start_date = new Date(currentBuild.startTimeInMillis + one_day_in_ms)
> 
> 	/*  Gets week number and cast it to integer. */
> ```

casts
___
*[jenkins/scripts/createNamespace.sh, line 122 at r16](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MflhcNu3EHyCcI3dSMu:-MflhcNu3EHyCcI3dSMv:bs88zv3) ([raw file](https://github.com/pmem/dev-utils-kit/blob/eca4cc87a120ea0cb3a2322e3a17fea34a53bad7/jenkins/scripts/createNamespace.sh#L122)):*
> ```Shell
> fi
> 
> # Due to requirements for some tests, it is required to have at least RO access
> ```

`some tests` bothers me. The reference mentions DeviceDAX tests but I would argue not all DeviceDAX tests have these requirements. Can we be any more specific?
___
*[jenkins/scripts/removeNamespaces.sh, line 10 at r16](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MfliQUS-wff2iP-Glcw:-MfliQUS-wff2iP-Glcx:bn7l20g) ([raw file](https://github.com/pmem/dev-utils-kit/blob/eca4cc87a120ea0cb3a2322e3a17fea34a53bad7/jenkins/scripts/removeNamespaces.sh#L10)):*
> ```Shell
> echo "Clearing all existing namespaces"
> MOUNTPOINTS=$(lsblk | grep "pmem" | grep "/" | tr -s ' ' | cut -d ' ' -f 7)
> ```

No newline is needed here. It is a sequence.
___
*[jenkins/scripts/removeNamespaces.sh, line 15 at r16](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-Mfliunc1Pt5-Cti2hv5:-Mfliunc1Pt5-Cti2hv6:b3eby20) ([raw file](https://github.com/pmem/dev-utils-kit/blob/eca4cc87a120ea0cb3a2322e3a17fea34a53bad7/jenkins/scripts/removeNamespaces.sh#L15)):*
> ```Shell
> done
> 
> namespace_names=$(ndctl list -X | jq -r '.[].dev')
> ```

You either name variables using capital letters or not.
___
*[jenkins/scripts/removeNamespaces.sh, line 16 at r16](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-Mfliu2J520hw7Rsulet:-Mfliu2J520hw7Rsuleu:bn7l20g) ([raw file](https://github.com/pmem/dev-utils-kit/blob/eca4cc87a120ea0cb3a2322e3a17fea34a53bad7/jenkins/scripts/removeNamespaces.sh#L16)):*
> ```Shell
> 
> namespace_names=$(ndctl list -X | jq -r '.[].dev')
> ```

No newline is needed here. It is a sequence.


<!-- Sent from Reviewable.io -->

2021-08-03 10:32 UTC, tszczyp reviewed
@lukaszstolarczuk, we came to the conclusion, that it would be the best to make bigger changes or reworks by creating an issue as you suggested. For now, I'll focus on fixing the remaining bugs/typos from the comments.

> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-:-MgAY92v9JhJLSlPrfQE:b-yk5xon)* status: all files reviewed, 12 unresolved discussions (waiting on @mramotowski, @nedved1, and @tszczyp)



<!-- Sent from Reviewable.io -->

2021-08-04 10:34 UTC, tszczyp reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1)* status: 3 of 7 files reviewed, 12 unresolved discussions (waiting on @janekmi, @KFilipek, @lukaszstolarczuk, @mramotowski, and @nedved1)

___
*[jenkins/README.md, line 14 at r16](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MflMi8H4G5Byijltzrh:-MgFhnN6CmYwQAgOwBan:b-896fix) ([raw file](https://github.com/pmem/dev-utils-kit/blob/eca4cc87a120ea0cb3a2322e3a17fea34a53bad7/jenkins/README.md#L14)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

the links
</blockquote></details>

Done.
___
*[jenkins/README.md, line 91 at r16](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MflaxAE5vxpmc8KAHe_:-MgFhsFd03LcTZIu37sB:b-896fix) ([raw file](https://github.com/pmem/dev-utils-kit/blob/eca4cc87a120ea0cb3a2322e3a17fea34a53bad7/jenkins/README.md#L91)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

only after creating this job, for the first tim -> when running the job for the first time
</blockquote></details>

Done.
___
*[jenkins/lib/api.groovy, line 142 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPygcM2zSVDiM05wwG:-MgFi0AH6bUCberz0Buj:b6pdy8r) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/lib/api.groovy#L142)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

So please describe what this function is good for in the comment.
</blockquote></details>

Added description based on @nedved1 comment.
___
*[jenkins/lib/api.groovy, line 28 at r16](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-Mflb712DlHc_l47qUuq:-MgFhwZn5Y0SbNOhZbOs:b-896fix) ([raw file](https://github.com/pmem/dev-utils-kit/blob/eca4cc87a120ea0cb3a2322e3a17fea34a53bad7/jenkins/lib/api.groovy#L28)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

a list of dicts
</blockquote></details>

Done.
___
*[jenkins/lib/api.groovy, line 388 at r16](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MfldWvC2ezv2dWMMXnP:-MgFiBi_A42oqIJZJCLw:b-896fix) ([raw file](https://github.com/pmem/dev-utils-kit/blob/eca4cc87a120ea0cb3a2322e3a17fea34a53bad7/jenkins/lib/api.groovy#L388)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

casts
</blockquote></details>

Done.
___
*[jenkins/scripts/createNamespace.sh, line 122 at r16](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MflhcNu3EHyCcI3dSMu:-MgFiFx76zRI5CrSCqBa:bqoq99i) ([raw file](https://github.com/pmem/dev-utils-kit/blob/eca4cc87a120ea0cb3a2322e3a17fea34a53bad7/jenkins/scripts/createNamespace.sh#L122)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`some tests` bothers me. The reference mentions DeviceDAX tests but I would argue not all DeviceDAX tests have these requirements. Can we be any more specific?
</blockquote></details>

Expanded an entire description, added missing file permissions as well.
___
*[jenkins/scripts/removeNamespaces.sh, line 10 at r16](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MfliQUS-wff2iP-Glcw:-MgFia022Aq31iSHGmQZ:b-896fix) ([raw file](https://github.com/pmem/dev-utils-kit/blob/eca4cc87a120ea0cb3a2322e3a17fea34a53bad7/jenkins/scripts/removeNamespaces.sh#L10)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

No newline is needed here. It is a sequence.
</blockquote></details>

Done.
___
*[jenkins/scripts/removeNamespaces.sh, line 15 at r16](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-Mfliunc1Pt5-Cti2hv5:-MgFibEe-9O2wQ-RcbwW:b-896fix) ([raw file](https://github.com/pmem/dev-utils-kit/blob/eca4cc87a120ea0cb3a2322e3a17fea34a53bad7/jenkins/scripts/removeNamespaces.sh#L15)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You either name variables using capital letters or not.
</blockquote></details>

Done.
___
*[jenkins/scripts/removeNamespaces.sh, line 16 at r16](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-Mfliu2J520hw7Rsulet:-MgFicKb6Dv5pSxhb5Mk:b-896fix) ([raw file](https://github.com/pmem/dev-utils-kit/blob/eca4cc87a120ea0cb3a2322e3a17fea34a53bad7/jenkins/scripts/removeNamespaces.sh#L16)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

No newline is needed here. It is a sequence.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-09 08:18 UTC, lukaszstolarczuk reviewed
ok, it makes sense, so please file the issue and describe what more could be done in this area.

> Reviewed 4 of 4 files at r17.
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-:-MgdxbxV1ivuUfGBB5ke:b-gs7crk)* status: all files reviewed, 12 unresolved discussions (waiting on @janekmi, @mramotowski, and @tszczyp)

___
*[jenkins/lib/api.groovy, line 142 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPygcM2zSVDiM05wwG:-MgdyHGa9vVcRdxjcsyJ:b5yl5cn) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/lib/api.groovy#L142)):*
<details><summary><i>Previously, tszczyp (Tomasz Szczypiorowski) wrote…</i></summary><blockquote>

Added description based on @nedved1 comment.
</blockquote></details>

please break the long line
___
*[jenkins/lib/api.groovy, line 360 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZQ20Sg-XIVDuWPBu6v:-Mgdylaf4xkh8aQs_W3N:bgg56j2) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/lib/api.groovy#L360)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Srsly Jenkins ignores the system configuration on this matter? You are absolutely sure?
</blockquote></details>

 @tszczyp, bump


<!-- Sent from Reviewable.io -->

2021-08-12 14:42 UTC, nedved1 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1)* status: all files reviewed, 12 unresolved discussions (waiting on @janekmi, @mramotowski, and @tszczyp)

___
*[jenkins/lib/api.groovy, line 360 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZQ20Sg-XIVDuWPBu6v:-MguVHSy9Ipo-r6jxgIe:b-ym5d4z) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/lib/api.groovy#L360)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

 @tszczyp, bump
</blockquote></details>

Jenkins Groovy scripts runs inside the Jenkins JVM or JVM on slave node.  Apparently it does not use host configuration.


<!-- Sent from Reviewable.io -->

2021-08-13 07:47 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1)* status: all files reviewed, 12 unresolved discussions (waiting on @janekmi, @mramotowski, and @tszczyp)

___
*[jenkins/lib/api.groovy, line 360 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZQ20Sg-XIVDuWPBu6v:-MgyTQKz0ovIi8sVu4WD:bxy7yoq) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/lib/api.groovy#L360)):*
<details><summary><i>Previously, nedved1 (Pawel Niedzwiecki) wrote…</i></summary><blockquote>

Jenkins Groovy scripts runs inside the Jenkins JVM or JVM on slave node.  Apparently it does not use host configuration.
</blockquote></details>

hmm... I see, this is still very weird it has to use milliseconds to set the date :wink: 


<!-- Sent from Reviewable.io -->

2021-08-23 11:03 UTC, janekmi requested changes
> Reviewed 4 of 4 files at r17.
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1)* status: all files reviewed, 5 unresolved discussions (waiting on @mramotowski and @tszczyp)

___
*[jenkins/lib/api.groovy, line 140 at r17](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MhmaybI0KP7LJQ6Syg-:-MhmaybI0KP7LJQ6Syg0:bf4p804) ([raw file](https://github.com/pmem/dev-utils-kit/blob/d24e00e622429de7e3811209c9b6a9e26120f72d/jenkins/lib/api.groovy#L140)):*
> ```Groovy
> /**
>  * Prints provided text to the output log.
>  * Used for markings in the standard output (Logs from build, tests, system_info, etc. are stored additionally on tested server - for later usage and archiving purposes).
> ```

Used for logs that are intended to be stored additionally on the tested server e.g. for later use or archiving purposes.
___
*[jenkins/scripts/createNamespace.sh, line 119 at r17](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-Mhme7a11aCBEVXJm5Kf:-Mhme7a2-S34lEfjJ_ou:b-leg8mj) ([raw file](https://github.com/pmem/dev-utils-kit/blob/d24e00e622429de7e3811209c9b6a9e26120f72d/jenkins/scripts/createNamespace.sh#L119)):*
> ```Shell
> 	fi
> 
> 	echo "Mount point: ${MOUNTPOINT}"
> ```

This should be printed only if `$CREATE_PMEM` is set?
Why not unconditionally?


<!-- Sent from Reviewable.io -->

2021-09-01 13:41 UTC, tszczyp reviewed
Sorry for long delays, by all means I can file an issue, but the question remains - what exactly do you expect to be changed in the bigger scale? I'm just following @mramotowski previous comments in this regard, so I'd like to ask you to provide more information (overall or specific) of what should be done. The current version will work, but I'm uncertain of what you'd like to see in the future.

> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-:-MiWYnO7DbTw1Sd9HlRq:b-m1bur8)* status: 6 of 7 files reviewed, 5 unresolved discussions (waiting on @janekmi, @lukaszstolarczuk, and @mramotowski)

___
*[jenkins/lib/api.groovy, line 142 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZPygcM2zSVDiM05wwG:-MiWW2Z6C4aO2mM-8G-T:b-u11168) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/lib/api.groovy#L142)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

please break the long line
</blockquote></details>

Updated line is not as long now :)
___
*[jenkins/lib/api.groovy, line 360 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZQ20Sg-XIVDuWPBu6v:-MiWW9H97LjS3XaD0GU5:b-7qpyu5) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/lib/api.groovy#L360)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

hmm... I see, this is still very weird it has to use milliseconds to set the date :wink: 
</blockquote></details>

So, can this comment be resolved or do you have more questions? :D
___
*[jenkins/lib/api.groovy, line 140 at r17](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MhmaybI0KP7LJQ6Syg-:-MiWW0Xg0iuCEFTce1TP:b499q7j) ([raw file](https://github.com/pmem/dev-utils-kit/blob/d24e00e622429de7e3811209c9b6a9e26120f72d/jenkins/lib/api.groovy#L140)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Used for logs that are intended to be stored additionally on the tested server e.g. for later use or archiving purposes.
</blockquote></details>

Changed
___
*[jenkins/scripts/createNamespace.sh, line 119 at r17](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-Mhme7a11aCBEVXJm5Kf:-MiWWlGs4vYqhcLy06Z0:b5mdria) ([raw file](https://github.com/pmem/dev-utils-kit/blob/d24e00e622429de7e3811209c9b6a9e26120f72d/jenkins/scripts/createNamespace.sh#L119)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This should be printed only if `$CREATE_PMEM` is set?
Why not unconditionally?
</blockquote></details>

Yes, because the mountpoints are created only if the fsdax namespaces are made as well, so there is not exactly any other occasion or need for them to be printed. 


<!-- Sent from Reviewable.io -->

2021-09-02 09:02 UTC, lukaszstolarczuk reviewed
For now, please just write in this issue what mramotowski pointed. We can always extend this issue with more info later on.

> Reviewed 1 of 1 files at r18.
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-:-Mi_h3vI1asbMHlrBVyD:b5c397j)* status: all files reviewed, 5 unresolved discussions (waiting on @janekmi and @mramotowski)



<!-- Sent from Reviewable.io -->

2021-09-06 10:31 UTC, tszczyp reviewed
All right, I've submitted an issue with information gathered from comments:
https://github.com/pmem/dev-utils-kit/issues/2

> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-:-MiueKJ84AS33jWuTUaI:bvqmv0e)* status: all files reviewed, 5 unresolved discussions (waiting on @janekmi and @mramotowski)

___
*[jenkins/lib/api.groovy, line 50 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZNfyzJ0zTeKozd9LpA:-MiueA342qwTf_Jxkxpo:b7nksbl) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/lib/api.groovy#L50)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I'm accepting this only to merge this PR at last.
</blockquote></details>

I've submitted an issue as requested:
https://github.com/pmem/dev-utils-kit/issues/2


<!-- Sent from Reviewable.io -->

2021-09-06 14:11 UTC, lukaszstolarczuk reviewed
at last, I think it looks good now, thanks
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-:-MivRNeA49V_Q6RzRpyD:b-4vvffo)* status: all files reviewed, 5 unresolved discussions (waiting on @janekmi and @mramotowski)



<!-- Sent from Reviewable.io -->

2021-09-06 14:37 UTC, mramotowski reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-:-MivXb_5CwcE_OYTwYf_:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2021-09-07 11:04 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1)* status: all files reviewed, 1 unresolved discussion (waiting on @tszczyp)

___
*[jenkins/lib/api.groovy, line 360 at r12](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-MZQ20Sg-XIVDuWPBu6v:-Mizv2bb1VjvQG-OIf_T:btjfqv2) ([raw file](https://github.com/pmem/dev-utils-kit/blob/fed29f064fd2a3b4a9a1ff0975d446ddb6366501/jenkins/lib/api.groovy#L360)):*
<details><summary><i>Previously, tszczyp (Tomasz Szczypiorowski) wrote…</i></summary><blockquote>

So, can this comment be resolved or do you have more questions? :D
</blockquote></details>

It looks strange, to say the least. But I turn a blind eye to it.
___
*[jenkins/scripts/createNamespace.sh, line 112 at r18](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-Mizuu6s9GhELwMpHKlo:-Mizuu6s9GhELwMpHKlp:bz1037p) ([raw file](https://github.com/pmem/dev-utils-kit/blob/ffbbd7997c4e243834124e47301ddd5c561f2c75/jenkins/scripts/createNamespace.sh#L112)):*
> ```Shell
> 	if [ ! -d "$MOUNTPOINT" ]; then
> 		sudo mkdir $MOUNTPOINT
> 	fi
> ```

In line #102 you call the `create_fsdax()` function which makes use of the `$MOUNTPOINT`. But in line #110 you are not so sure the `$MOUNTPOINT` still exists so you call `mkdir` just in case.


<!-- Sent from Reviewable.io -->

2021-09-08 08:42 UTC, tszczyp reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @janekmi and @lukaszstolarczuk)

___
*[jenkins/scripts/createNamespace.sh, line 112 at r18](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-Mizuu6s9GhELwMpHKlo:-Mj3ZR8k2susNCbPxRhd:b-s869ki) ([raw file](https://github.com/pmem/dev-utils-kit/blob/ffbbd7997c4e243834124e47301ddd5c561f2c75/jenkins/scripts/createNamespace.sh#L112)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

In line #102 you call the `create_fsdax()` function which makes use of the `$MOUNTPOINT`. But in line #110 you are not so sure the `$MOUNTPOINT` still exists so you call `mkdir` just in case.
</blockquote></details>

The newest change should clear this up a little


<!-- Sent from Reviewable.io -->

2021-09-08 09:11 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 1 files at r19.
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2021-09-09 11:20 UTC, janekmi requested changes
> Reviewed 1 of 1 files at r19.
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1)* status: all files reviewed, 1 unresolved discussion (waiting on @tszczyp)

___
*[jenkins/scripts/createNamespace.sh, line 93 at r19](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-Mj9H9uKEon1qZIfuL68:-Mj9H9uKEon1qZIfuL69:bh364ff) ([raw file](https://github.com/pmem/dev-utils-kit/blob/6526d60a42d914708d83d9c08544bf1a2ca43a05/jenkins/scripts/createNamespace.sh#L93)):*
> ```Shell
> 	create_devdax 4k $SIZE
> 	# Setting DAX specific permission.
> 	sudo chmod 777 /dev/dax*
> ```

I do not see a point in this enhancement.


<!-- Sent from Reviewable.io -->

2021-09-13 11:08 UTC, KFilipek commented
> > Reviewed 1 of 1 files at r19.
> > _[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1)_ status: all files reviewed, 1 unresolved discussion (waiting on @tszczyp)
> 
> _[jenkins/scripts/createNamespace.sh, line 93 at r19](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-Mj9H9uKEon1qZIfuL68:-Mj9H9uKEon1qZIfuL69:bh364ff) ([raw file](https://github.com/pmem/dev-utils-kit/blob/6526d60a42d914708d83d9c08544bf1a2ca43a05/jenkins/scripts/createNamespace.sh#L93)):_
> 
> > ```shell
> > 	create_devdax 4k $SIZE
> > 	# Setting DAX specific permission.
> > 	sudo chmod 777 /dev/dax*
> > ```
> 
> I do not see a point in this enhancement.

777 also should be avoided anyway.
I see some catastrophic cases like: add nopass executable with root privileges and place it under "777" directory, free backdoor installed. Most of security weaknesses are made by many wrong decisions.

2021-09-14 13:31 UTC, tszczyp reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @janekmi and @lukaszstolarczuk)

___
*[jenkins/scripts/createNamespace.sh, line 93 at r19](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-Mj9H9uKEon1qZIfuL68:-MjZQraL6yRUWJF_RzQN:b-3go2z6) ([raw file](https://github.com/pmem/dev-utils-kit/blob/6526d60a42d914708d83d9c08544bf1a2ca43a05/jenkins/scripts/createNamespace.sh#L93)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

777 also should be avoided anyway.
I see some catastrophic cases like: add nopass executable with root privileges and place it under "777" directory, free backdoor installed. Most of security weaknesses are made by many wrong decisions.

</blockquote></details>

 /dev/dax permissions were moved to the place where they are created, as methods should return only a name of created dax. In case of fsdax and pmems, we deleted one 'if' and relocated mountpoint permissions to line 112.
Also changed chmod permissions to 666.


<!-- Sent from Reviewable.io -->

2021-09-14 13:38 UTC, tszczyp reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @janekmi and @lukaszstolarczuk)

___
*[jenkins/scripts/createNamespace.sh, line 93 at r19](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-Mj9H9uKEon1qZIfuL68:-MjZWjtR940Q-3AoXjct:b-lby86k) ([raw file](https://github.com/pmem/dev-utils-kit/blob/6526d60a42d914708d83d9c08544bf1a2ca43a05/jenkins/scripts/createNamespace.sh#L93)):*
<details><summary><i>Previously, tszczyp (Tomasz Szczypiorowski) wrote…</i></summary><blockquote>

 /dev/dax permissions were moved to the place where they are created, as methods should return only a name of created dax. In case of fsdax and pmems, we deleted one 'if' and relocated mountpoint permissions to line 112.
Also changed chmod permissions to 666.
</blockquote></details>

To clarify in advance, 666 is the rw access to all users
![image.png](https://files.reviewableusercontent.io/images/reviewable/25879106/f-eGyiAR93vUN3jINXY-hde4/image.png)


<!-- Sent from Reviewable.io -->

2021-09-21 09:34 UTC, janekmi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r20.
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-:-Mk6hFTs-I3GJg1Vr1IV:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tszczyp)



<!-- Sent from Reviewable.io -->

2021-09-21 11:41 UTC, KFilipek reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> once again

> Reviewed 1 of 4 files at r16, 2 of 4 files at r17, 1 of 1 files at r18, 1 of 1 files at r20.
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1#-:-Mk79GWk190Ma-u_3O1Q:b-vbjjv4)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tszczyp)



<!-- Sent from Reviewable.io -->

2021-09-21 12:55 UTC, janekmi approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tszczyp)



<!-- Sent from Reviewable.io -->

2021-09-21 12:58 UTC, merged